export const UI_THEME = {
  bg0: '#050709',
  bg1: '#080C0F',
  bg2: '#0C1217',
  bg3: '#111920',
  bg4: '#182028',
  panel: '#10171D',
  card: '#141D24',
  hover: '#1B2630',
  accent: '#D4561E',
  accentHi: '#F06428',
  accentSoft: 'rgba(212,86,30,.16)',
  gold: '#E8C84A',
  goldSoft: 'rgba(232,200,74,.14)',
  white: '#F2EDE4',
  ink: '#F2EDE4',
  dim: 'rgba(242,237,228,.62)',
  faint: 'rgba(242,237,228,.30)',
  ghost: 'rgba(242,237,228,.08)',
  line: 'rgba(242,237,228,.07)',
  lineMid: 'rgba(242,237,228,.14)',
  display: "'Bebas Neue', sans-serif",
  cond: "'Barlow Condensed', sans-serif",
  body: "'Barlow', sans-serif",
  mono: "'Space Mono', monospace",
};

export const SURFACE_THEME = {
  CLAY: { main: '#D4561E', light: '#F06428', glow: 'rgba(212,86,30,.35)', label: 'Saibro' },
  GRASS: { main: '#2E7D32', light: '#43A047', glow: 'rgba(46,125,50,.35)', label: 'Grama' },
  HARD: { main: '#2860A8', light: '#4A90D9', glow: 'rgba(40,96,168,.35)', label: 'Dura' },
  INDOOR: { main: '#8B2FAA', light: '#C84FEB', glow: 'rgba(139,47,170,.35)', label: 'Indoor' },
};

export const HOME_THEME = {
  ...UI_THEME,
  ink1: UI_THEME.bg1,
  ink2: UI_THEME.bg2,
  ink3: UI_THEME.bg3,
  ink4: UI_THEME.bg4,
  clay: UI_THEME.accent,
  clayHi: UI_THEME.accentHi,
  clayLo: '#8B3410',
  chalk: UI_THEME.white,
  line: UI_THEME.line,
  lineMid: UI_THEME.lineMid,
  D: UI_THEME.display,
  Bc: UI_THEME.cond,
  B: UI_THEME.body,
  M: UI_THEME.mono,
};

export const BROADCAST_THEME = {
  ...UI_THEME,
  bg: UI_THEME.bg0,
  bgDeep: '#030507',
  bgMid: UI_THEME.bg1,
  bgPanel: UI_THEME.bg2,
  bgCard: UI_THEME.bg3,
  bgLight: UI_THEME.bg4,
  bgHover: UI_THEME.bg4,
  clay: UI_THEME.accent,
  clayLight: UI_THEME.accentHi,
  clayGlow: SURFACE_THEME.CLAY.glow,
  grass: SURFACE_THEME.GRASS.main,
  grassLight: SURFACE_THEME.GRASS.light,
  grassGlow: SURFACE_THEME.GRASS.glow,
  hard: SURFACE_THEME.HARD.main,
  hardLight: SURFACE_THEME.HARD.light,
  hardGlow: SURFACE_THEME.HARD.glow,
  indoor: SURFACE_THEME.INDOOR.main,
  indoorLight: SURFACE_THEME.INDOOR.light,
  indoorGlow: SURFACE_THEME.INDOOR.glow,
  goldDim: 'rgba(232,200,74,.55)',
  goldFaint: UI_THEME.goldSoft,
  textDim: UI_THEME.dim,
  textFaint: UI_THEME.faint,
  border: UI_THEME.line,
  borderMid: UI_THEME.lineMid,
  disp: UI_THEME.display,
  cond: UI_THEME.cond,
  body: UI_THEME.body,
  mono: UI_THEME.mono,
};

export const PROFILE_THEME = {
  ...BROADCAST_THEME,
  bg0: UI_THEME.bg0,
  bg1: UI_THEME.bg1,
  bg2: UI_THEME.bg2,
  bg3: UI_THEME.bg3,
  bg4: UI_THEME.bg4,
  ink: UI_THEME.ink,
  inkDim: UI_THEME.dim,
  inkFaint: UI_THEME.faint,
  inkGhost: UI_THEME.ghost,
  line: UI_THEME.line,
  lineMid: UI_THEME.lineMid,
  display: UI_THEME.display,
};

export const ARCHIVE_THEME = {
  ...BROADCAST_THEME,
  paper: '#0D1319',
  card: '#121B22',
  cream: '#EDE6D8',
  serif: "'Cormorant Garamond', 'Cormorant', Georgia, serif",
  sans: UI_THEME.cond,
};

export const ANALYTICS_THEME = {
  ...BROADCAST_THEME,
  bg: '#07100D',
  bgMid: '#0D1715',
  bgPanel: '#101A18',
  bgLight: '#17231F',
  green: '#00C48C',
  red: '#EF4444',
  yellow: '#FFD700',
  blue: '#00D4FF',
  display: UI_THEME.cond,
  body: UI_THEME.body,
  mono: UI_THEME.mono,
};
