export const SHOT_TUNING_VERSION = 'shot-tuning-realism-v4';

export const SHOT_TUNING = Object.freeze({
  quality: Object.freeze({
    // A qualidade não pode saturar todo contato limpo em 100%. O piso de
    // contato continua protegendo a fluidez, mas a execução técnica agora
    // permanece visível entre dois jogadores bem posicionados.
    globalMultiplier: 0.82,
  }),

  realism: Object.freeze({
    rally: Object.freeze({
      baseSigmaX: 0.62,
      baseSigmaY: 0.92,
      deepSigmaY: 0.72,
      shortSigmaY: 0.52,
      centerSigmaX: 0.54,
      attackSigmaMult: 0.82,
      defenseSigmaMult: 1.34,
      lowQualitySpread: 0.70,
      highQualityTighten: 0.24,
      pressureSpread: 0.42,
      surfaceSpread: 0.55,
      humanTailChance: 0.16,
      humanTailMult: 2.15,
      safeDepthBias: 0.34,
      crossDepthBias: 0.18,
      dtlLineBias: 0.34,
      angleShortBias: 0.58,
      bodyJitter: 0.58,
    }),
    serve: Object.freeze({
      firstSigmaX: 0.24,
      firstSigmaY: 0.32,
      secondSigmaX: 0.14,
      secondSigmaY: 0.20,
      flatLineBias: 0.08,
      sliceWideBias: 0.14,
      kickDeepBias: 0.08,
      bodyJitter: 0.22,
      precisionTighten: 0.46,
      powerSpread: 0.10,
      humanTailChance: 0.055,
      humanTailMult: 1.45,
    }),
    error: Object.freeze({
      normalNoiseMult: 0.38,
      lateralIntentWeight: 0.74,
      depthIntentWeight: 0.82,
      flatLongBias: 0.64,
      topspinShortBias: 0.34,
      sliceDepthChaos: 0.58,
      dropDepthChaos: 0.72,
      dtlWideBias: 0.78,
      wideTargetWideBias: 0.62,
      defendShortBias: 0.42,
    }),
  }),

  execution: Object.freeze({
    powerBase: 10,
    paceBiasPower: 16,
    wingPower: 8,
    qualityPower: 5,
    finishPowerBonus: 4.0,
    pressurePowerBonus: 2.4,
    finishMarginPowerCapLowQ: 28.2,
    finishMarginPowerCapMidQ: 31.0,
    finishMarginPowerCapHighQ: 34.0,
    finishMarginPowerPenaltyLowQ: -2.8,
    finishMarginPowerPenaltyMidQ: -1.1,
    defendPowerPenalty: -2.0,
    minPower: 7.0,
    maxPower: 38,
    topspinBase: 0.45,
    topspinAttr: 0.95,
    backspinBase: 0.35,
    backspinAttr: 0.90,
    sidespinBase: 0.25,
    sidespinAttr: 0.70,
    topspinToSpinX: 0.34,
    backspinToSpinX: 0.30,
    sidespinToSpinZ: 0.20,
    minTopspinX: 0.4,
    minBackspinX: 0.6,
    minHitHeight: 0.44,
    maxHitHeight: 2.35,
    qualityNetSafety: 0.18,
    topspinNetSafety: 0.10,
    minNetClearance: 0.22,
    maxNetClearance: 2.55,
  }),

  errors: Object.freeze({
    attrErrorRelief: 0.22,
    spinSecurityRelief: 0.10,
    bodyPenalty: 0.48,
    baseRiskWeight: 0.34,
    minRisk: 0.02,
    maxRisk: 0.92,
    dispersionBase: 1.20,
    dispersionControlRelief: 0.55,
    minDispersion: 0.02,
    maxDispersion: 0.95,
    lateralNoise: 1.15,
    depthNoise: 1.85,
    netNoise: 0.26,
    paceNoise: 2.2,
    highRiskNetPenaltyStart: 0.58,
    highRiskNetPenalty: 0.22,
    degradedMinNetClearance: 0.01,
    degradedMaxNetClearance: 2.8,
    degradedMinPower: 5.5,
    degradedMaxPower: 46,
  }),

  serve: Object.freeze({
    targetDepth: 0.70,
    flatTargetDepth: 0.76,
    sliceTargetDepth: 0.66,
    kickTargetDepth: 0.78,
    targetWideX: 2.78,
    targetBodyX: 1.35,
    targetCenterX: 0.42,
    stanceX: 1.18,
    serverBackY: 0.18,
    receiverX: 2.15,
    receiverBackY: 2.55,
    qualityPrecision: 0.44,
    qualityPower: 0.26,
    qualityMentality: 0.18,
    qualityStamina: 0.12,
    powerBase: 28,
    powerAttr: 25,
    qualityPowerBonus: 4,
    firstServeBoost: 1.0,
    secondServeBoost: 0.82,
    flatPace: 1.0,
    slicePace: 0.82,
    kickPace: 0.72,
    minPower: 22,
    firstMaxPower: 58,
    secondMaxPower: 44,
    flatNetClearance: 0.58,
    sliceNetClearance: 0.78,
    kickNetClearance: 1.08,
    hitHeight: 2.42,
    flatSpinX: -0.09,
    sliceSpinX: -0.16,
    sliceSpinZBase: 0.34,
    sliceSpinZAttr: 0.32,
    kickSpinXBase: 0.46,
    kickSpinXAttr: 0.36,
    kickSpinZ: 0.16,
  }),

  return: Object.freeze({
    pressureSpeedDivisor: 40,
    blockPressure: 0.74,
    poorQualityBlock: 0.48,
    attackSecondServeQuality: 0.60,
    attackReturnSkill: 0.58,
    aggressiveQuality: 0.72,
    crossQuality: 0.68,
    scoreQualityWeight: 0.58,
    scoreSkillWeight: 0.42,
    pressureScorePenalty: 0.18,
    directMissBase: 0.032,
    directMissPressure: 0.23,
    directMissQualityRelief: 0.28,
    easyReturnQuality: 0.60,
    floatShortPressure: 0.76,
    weakReturnScore: 0.58,
    attackFirstServeQuality: 0.74,
    attackFirstServeMaxPressure: 0.54,
    attackFirstServeMaxKmh: 162,
    attackSecondServeMaxKmh: 176,
    returnDrivePowerCap: 27.5,
    returnCounterPowerCap: 26.5,
    returnBlockPowerCap: 18.2,
    returnChipPowerCap: 20.5,
  }),

  rallyEV: Object.freeze({
    qualityWeight: 0.44,
    readinessWeight: 0.30,
    arrivalWeight: 0.20,
    preparedBonus: 0.08,
    latePenalty: 0.17,            // era 0.26 — penalidade excessiva colapsava safetyEV em timing normal
    lowPickupPenalty: 0.12,
    lowAttackablePenalty: 0.03,
    pressureSafetyPenalty: 0.20,
    playerWideSafetyPenalty: 0.10,
    rivalWideBonus: 0.30,
    rivalVeryWideBonus: 0.22,
    rivalDeepBonus: 0.28,         // era 0.20 — oponente fundo deve sinalizar oportunidade de ataque mais forte
    rivalVeryDeepBonus: 0.16,
    shortBallBonus: 0.34,
    safetyToPressure: 0.42,
    exposureToPressure: 0.52,
    rallyPressureBonus: 0.20,     // era 0.14 — rally longo deve gerar urgência de ataque mais cedo
    variationPressureBonus: 0.16,
    stylePressureBonus: 0.18,
    pressureAttackPenalty: 0.16,
    safetyToFinish: 0.28,
    exposureToFinish: 0.62,
    shortToFinish: 0.22,
    earlyFinishBonus: 0.12,
    rallyFinishBonus: 0.12,
    pressureFinishPenalty: 0.18,
    grinderFinishPenalty: 0.12,
    unsafeToDefense: 0.58,
    pressureToDefense: 0.34,
    lateDefenseBonus: 0.26,
    lowDefenseBonus: 0.08,
    wideDefenseBonus: 0.12,
    sliceLoopPressure: 0.16,
    softLoopPressure: 0.12,
    directionLoopPressure: 0.04,
    memoryPlanBonus: 0.18,
    longRallyAt: 8,               // era 10 — urgência de ataque matura mais cedo (rally 5-6 vs 8-10)
    longRallyVariation: 0.10,
    earlyStyleBonus: 0.28,
    grinderStylePenalty: 0.12,
    styleBiasWeight: 1.35,
    finishThreshold: 0.52,
    pressureThreshold: 0.46,
    attackSafetyThreshold: 0.34,
    opportunisticAttackSafety: 0.22,
    resetSafetyThreshold: 0.22,
    defendThreshold: 0.78,
    controlSafetyThreshold: 0.30,
    controlVariationThreshold: 0.34,
    desperateQuality: 0.30,
    desperatePressure: 0.88,
    preparedReadiness: 0.58,
    preparedSettle: 0.14,
    cleanQuality: 0.45,
    cleanArrivalMargin: -0.035,
    lateArrivalMargin: -0.120,    // era -0.085 — 85ms tarde acionava DEFEND; 120ms é timing real de corrida
    lowBallZ: 0.48,
    shortBallY: 8.0,
    playerWideX: 3.72,            // era 3.10 — jogador a 1m da lateral não é "wide em duress"; ~0.4m da linha é razoável
    rivalWideX: 1.45,
    rivalVeryWideX: 2.35,
    rivalDeepY: 9.15,
    rivalVeryDeepY: 10.30,
    serveAdvPressureWeight: 0.26,
    serveAdvFinishWeight: 0.17,
    easyReturnPressureBonus: 0.12,
    easyReturnFinishBonus: 0.13,
    serveAdvStyleWeight: 0.03,
    serveAdvSafetyPenalty: 0.12,
    momentumPressureWeight: 0.045,
    momentumStyleWeight: 0.035,
    stateFinishThreshold: 0.52,
    statePressureThreshold: 0.46,
    stateConstructionSafety: 0.30,
    stateResetSafety: 0.22,
  }),
});

export function shotTuningSummary() {
  return Object.freeze({
    version: SHOT_TUNING_VERSION,
    sections: Object.freeze(Object.keys(SHOT_TUNING)),
  });
}
