export const SHOT_TUNING_VERSION = 'shot-tuning-v1';

export const SHOT_TUNING = Object.freeze({
  execution: Object.freeze({
    powerBase: 10,
    paceBiasPower: 16,
    wingPower: 8,
    qualityPower: 5,
    finishPowerBonus: 4.0,
    pressurePowerBonus: 2.4,
    defendPowerPenalty: -2.0,
    minPower: 7.0,
    maxPower: 38,
    topspinBase: 0.45,
    topspinAttr: 0.95,
    backspinBase: 0.35,
    backspinAttr: 0.90,
    sidespinBase: 0.25,
    sidespinAttr: 0.70,
    topspinToSpinX: 0.34,
    backspinToSpinX: 0.30,
    sidespinToSpinZ: 0.20,
    minTopspinX: 0.4,
    minBackspinX: 0.6,
    minHitHeight: 0.44,
    maxHitHeight: 2.35,
    qualityNetSafety: 0.18,
    topspinNetSafety: 0.10,
    minNetClearance: 0.22,
    maxNetClearance: 2.55,
  }),

  errors: Object.freeze({
    attrErrorRelief: 0.22,
    spinSecurityRelief: 0.10,
    bodyPenalty: 0.48,
    baseRiskWeight: 0.34,
    minRisk: 0.02,
    maxRisk: 0.92,
    dispersionBase: 1.20,
    dispersionControlRelief: 0.55,
    minDispersion: 0.02,
    maxDispersion: 0.95,
    lateralNoise: 1.15,
    depthNoise: 1.85,
    netNoise: 0.26,
    paceNoise: 2.2,
    highRiskNetPenaltyStart: 0.58,
    highRiskNetPenalty: 0.22,
    degradedMinNetClearance: 0.01,
    degradedMaxNetClearance: 2.8,
    degradedMinPower: 5.5,
    degradedMaxPower: 46,
  }),

  serve: Object.freeze({
    targetDepth: 0.70,
    targetWideX: 3.05,
    targetBodyX: 1.35,
    targetCenterX: 0.42,
    stanceX: 1.18,
    serverBackY: 0.18,
    receiverX: 2.15,
    receiverBackY: 2.85,
    qualityPrecision: 0.44,
    qualityPower: 0.26,
    qualityMentality: 0.18,
    qualityStamina: 0.12,
    powerBase: 28,
    powerAttr: 25,
    qualityPowerBonus: 4,
    firstServeBoost: 1.0,
    secondServeBoost: 0.82,
    flatPace: 1.0,
    slicePace: 0.82,
    kickPace: 0.72,
    minPower: 22,
    firstMaxPower: 58,
    secondMaxPower: 44,
    flatNetClearance: 0.58,
    sliceNetClearance: 0.78,
    kickNetClearance: 1.08,
    hitHeight: 2.42,
    flatSpinX: -0.09,
    sliceSpinX: -0.18,
    sliceSpinZBase: 0.34,
    sliceSpinZAttr: 0.32,
    kickSpinXBase: 0.46,
    kickSpinXAttr: 0.36,
    kickSpinZ: 0.16,
  }),

  return: Object.freeze({
    pressureSpeedDivisor: 48,
    blockPressure: 0.74,
    poorQualityBlock: 0.48,
    attackSecondServeQuality: 0.60,
    attackReturnSkill: 0.58,
    aggressiveQuality: 0.72,
    crossQuality: 0.68,
    scoreQualityWeight: 0.58,
    scoreSkillWeight: 0.42,
    pressureScorePenalty: 0.18,
  }),

  rallyEV: Object.freeze({
    qualityWeight: 0.44,
    readinessWeight: 0.30,
    arrivalWeight: 0.20,
    preparedBonus: 0.08,
    latePenalty: 0.26,
    lowPickupPenalty: 0.18,
    pressureSafetyPenalty: 0.20,
    playerWideSafetyPenalty: 0.10,
    rivalWideBonus: 0.22,
    rivalVeryWideBonus: 0.16,
    rivalDeepBonus: 0.14,
    rivalVeryDeepBonus: 0.10,
    shortBallBonus: 0.26,
    safetyToPressure: 0.50,
    exposureToPressure: 0.40,
    rallyPressureBonus: 0.12,
    variationPressureBonus: 0.16,
    stylePressureBonus: 0.18,
    pressureAttackPenalty: 0.16,
    safetyToFinish: 0.36,
    exposureToFinish: 0.48,
    shortToFinish: 0.16,
    earlyFinishBonus: 0.08,
    rallyFinishBonus: 0.10,
    pressureFinishPenalty: 0.18,
    grinderFinishPenalty: 0.12,
    unsafeToDefense: 0.58,
    pressureToDefense: 0.34,
    lateDefenseBonus: 0.26,
    lowDefenseBonus: 0.16,
    wideDefenseBonus: 0.12,
    sliceLoopPressure: 0.16,
    softLoopPressure: 0.12,
    directionLoopPressure: 0.04,
    memoryPlanBonus: 0.18,
    longRallyAt: 10,
    longRallyVariation: 0.10,
    earlyStyleBonus: 0.28,
    grinderStylePenalty: 0.12,
    styleBiasWeight: 1.35,
    finishThreshold: 0.58,
    pressureThreshold: 0.50,
    attackSafetyThreshold: 0.48,
    resetSafetyThreshold: 0.34,
    defendThreshold: 0.66,
    controlSafetyThreshold: 0.42,
    controlVariationThreshold: 0.34,
    desperateQuality: 0.30,
    desperatePressure: 0.88,
    preparedReadiness: 0.58,
    preparedSettle: 0.14,
    cleanQuality: 0.45,
    cleanArrivalMargin: -0.035,
    lateArrivalMargin: -0.085,
    lowBallZ: 0.48,
    shortBallY: 8.0,
    playerWideX: 3.10,
    rivalWideX: 1.45,
    rivalVeryWideX: 2.35,
    rivalDeepY: 9.15,
    rivalVeryDeepY: 10.30,
  }),
});

export function shotTuningSummary() {
  return Object.freeze({
    version: SHOT_TUNING_VERSION,
    sections: Object.freeze(Object.keys(SHOT_TUNING)),
  });
}
