import { ShotFamily, ShotIntent, RiskProfile } from './ShotTypes.js';

export const SHOT_CATALOG = Object.freeze({
  [ShotFamily.TOPSPIN]: Object.freeze({
    family: ShotFamily.TOPSPIN,
    label: 'Topspin',
    mechanics: 'groundstroke',
    primaryAttr: 'topspin',
    controlAttr: 'wingControl',
    powerAttr: 'wingPower',
    // Topspin alto e profundo é a bola-padrão para sobreviver e reiniciar
    // uma troca moderna. RESET não pode empurrar o motor automaticamente
    // para slice; slice é uma ferramenta situacional, não a troca inteira.
    intents: [ShotIntent.CONTROL, ShotIntent.BUILD, ShotIntent.RESET, ShotIntent.REDIRECT, ShotIntent.PRESSURE, ShotIntent.DEFEND, ShotIntent.PASS],
    baseRisk: 0.34,
    netClearance: 0.78,
    depthBias: 0.72,
    paceBias: 0.70,
    topspinBias: 0.86,
    backspinBias: 0,
    marginProfile: RiskProfile.NORMAL,
  }),
  [ShotFamily.FLAT_DRIVE]: Object.freeze({
    family: ShotFamily.FLAT_DRIVE,
    label: 'Flat Drive',
    mechanics: 'groundstroke',
    primaryAttr: 'wingPower',
    controlAttr: 'wingControl',
    powerAttr: 'wingPower',
    intents: [ShotIntent.REDIRECT, ShotIntent.PRESSURE, ShotIntent.FINISH, ShotIntent.BUILD, ShotIntent.PASS],
    baseRisk: 0.56,
    netClearance: 0.46,
    depthBias: 0.80,
    paceBias: 0.92,
    topspinBias: 0.28,
    backspinBias: 0,
    marginProfile: RiskProfile.AGGRESSIVE,
  }),
  [ShotFamily.SLICE]: Object.freeze({
    family: ShotFamily.SLICE,
    label: 'Slice',
    mechanics: 'groundstroke',
    primaryAttr: 'slice',
    controlAttr: 'wingControl',
    powerAttr: 'wingPower',
    intents: [ShotIntent.RESET, ShotIntent.DEFEND, ShotIntent.REDIRECT, ShotIntent.APPROACH],
    baseRisk: 0.30,
    netClearance: 0.42,
    depthBias: 0.64,
    paceBias: 0.50,
    topspinBias: 0,
    backspinBias: 0.88,
    marginProfile: RiskProfile.SAFE,
  }),
  [ShotFamily.LOB]: Object.freeze({
    family: ShotFamily.LOB,
    label: 'Lob',
    mechanics: 'arc',
    primaryAttr: 'touch',
    controlAttr: 'wingControl',
    powerAttr: 'wingPower',
    intents: [ShotIntent.DEFEND, ShotIntent.RESET, ShotIntent.PRESSURE, ShotIntent.PASS],
    baseRisk: 0.50,
    netClearance: 2.85,
    depthBias: 0.86,
    paceBias: 0.34,
    topspinBias: 0.58,
    backspinBias: 0.10,
    marginProfile: RiskProfile.SAFE,
  }),
  [ShotFamily.DROP]: Object.freeze({
    family: ShotFamily.DROP,
    label: 'Drop Shot',
    mechanics: 'touch',
    primaryAttr: 'touch',
    controlAttr: 'wingControl',
    powerAttr: 'slice',
    intents: [ShotIntent.PRESSURE, ShotIntent.FINISH, ShotIntent.BUILD, ShotIntent.CONTROL],
    baseRisk: 0.62,
    netClearance: 0.34,
    depthBias: 0.22,
    paceBias: 0.18,
    topspinBias: 0,
    backspinBias: 0.72,
    marginProfile: RiskProfile.AGGRESSIVE,
  }),
  [ShotFamily.VOLLEY]: Object.freeze({
    family: ShotFamily.VOLLEY,
    label: 'Volley',
    mechanics: 'aerial',
    primaryAttr: 'volley',
    controlAttr: 'volley',
    powerAttr: 'volley',
    intents: [ShotIntent.CONTROL, ShotIntent.PRESSURE, ShotIntent.FINISH],
    baseRisk: 0.42,
    netClearance: 0.30,
    depthBias: 0.48,
    paceBias: 0.58,
    topspinBias: 0.08,
    backspinBias: 0.18,
    marginProfile: RiskProfile.NORMAL,
  }),
  [ShotFamily.SMASH]: Object.freeze({
    family: ShotFamily.SMASH,
    label: 'Smash',
    mechanics: 'overhead',
    primaryAttr: 'smash',
    controlAttr: 'smash',
    powerAttr: 'smash',
    intents: [ShotIntent.FINISH],
    baseRisk: 0.50,
    netClearance: 0.38,
    depthBias: 0.64,
    paceBias: 0.96,
    topspinBias: 0.18,
    backspinBias: 0,
    marginProfile: RiskProfile.AGGRESSIVE,
  }),
  [ShotFamily.BLOCK_RETURN]: Object.freeze({
    family: ShotFamily.BLOCK_RETURN,
    label: 'Block Return',
    mechanics: 'return',
    primaryAttr: 'return',
    controlAttr: 'return',
    powerAttr: 'return',
    intents: [ShotIntent.RESET, ShotIntent.CONTROL],
    baseRisk: 0.28,
    netClearance: 0.48,
    depthBias: 0.52,
    paceBias: 0.44,
    topspinBias: 0.20,
    backspinBias: 0.12,
    marginProfile: RiskProfile.SAFE,
  }),
  [ShotFamily.CHIP_RETURN]: Object.freeze({
    family: ShotFamily.CHIP_RETURN,
    label: 'Chip Return',
    mechanics: 'return',
    primaryAttr: 'return',
    controlAttr: 'slice',
    powerAttr: 'return',
    intents: [ShotIntent.RESET, ShotIntent.CONTROL, ShotIntent.APPROACH],
    baseRisk: 0.34,
    netClearance: 0.38,
    depthBias: 0.52,
    paceBias: 0.34,
    topspinBias: 0,
    backspinBias: 0.56,
    marginProfile: RiskProfile.SAFE,
  }),
  [ShotFamily.SERVE_FLAT]: Object.freeze({
    family: ShotFamily.SERVE_FLAT,
    label: 'Flat Serve',
    mechanics: 'serve',
    primaryAttr: 'servePower',
    controlAttr: 'servePrecision',
    powerAttr: 'servePower',
    intents: [ShotIntent.PRESSURE, ShotIntent.FINISH],
    baseRisk: 0.64,
    netClearance: 0.54,
    depthBias: 0.78,
    paceBias: 1.0,
    topspinBias: 0.08,
    backspinBias: 0,
    marginProfile: RiskProfile.AGGRESSIVE,
  }),
  [ShotFamily.SERVE_SLICE]: Object.freeze({
    family: ShotFamily.SERVE_SLICE,
    label: 'Slice Serve',
    mechanics: 'serve',
    primaryAttr: 'slice',
    controlAttr: 'servePrecision',
    powerAttr: 'servePower',
    intents: [ShotIntent.PRESSURE, ShotIntent.BUILD],
    baseRisk: 0.46,
    netClearance: 0.68,
    depthBias: 0.66,
    paceBias: 0.78,
    topspinBias: 0.12,
    backspinBias: 0.22,
    sidespinBias: 0.86,
    marginProfile: RiskProfile.NORMAL,
  }),
  [ShotFamily.SERVE_KICK]: Object.freeze({
    family: ShotFamily.SERVE_KICK,
    label: 'Kick Serve',
    mechanics: 'serve',
    primaryAttr: 'topspin',
    controlAttr: 'servePrecision',
    powerAttr: 'servePower',
    intents: [ShotIntent.CONTROL, ShotIntent.BUILD, ShotIntent.PRESSURE],
    baseRisk: 0.36,
    netClearance: 0.92,
    depthBias: 0.62,
    paceBias: 0.62,
    topspinBias: 0.96,
    backspinBias: 0,
    marginProfile: RiskProfile.SAFE,
  }),
});

export const SHOT_FAMILIES = Object.freeze(Object.keys(SHOT_CATALOG));

export function getShotDefinition(family) {
  return SHOT_CATALOG[family] ?? null;
}

export function getFamiliesForPhase(phase) {
  if (phase === 'SERVE') {
    return [ShotFamily.SERVE_FLAT, ShotFamily.SERVE_SLICE, ShotFamily.SERVE_KICK];
  }
  if (phase === 'RETURN') {
    return [ShotFamily.BLOCK_RETURN, ShotFamily.CHIP_RETURN, ShotFamily.TOPSPIN, ShotFamily.FLAT_DRIVE, ShotFamily.SLICE];
  }
  if (phase === 'NET') {
    return [ShotFamily.VOLLEY, ShotFamily.SMASH];
  }
  if (phase === 'PASSING') {
    return [ShotFamily.TOPSPIN, ShotFamily.FLAT_DRIVE, ShotFamily.LOB, ShotFamily.SLICE];
  }
  if (phase === 'APPROACH') {
    return [ShotFamily.SLICE, ShotFamily.FLAT_DRIVE, ShotFamily.TOPSPIN, ShotFamily.DROP];
  }
  return [ShotFamily.TOPSPIN, ShotFamily.FLAT_DRIVE, ShotFamily.SLICE, ShotFamily.LOB, ShotFamily.DROP];
}
