import { ShotFamily } from './ShotTypes.js';

const DEFAULT_IDENTITY = Object.freeze({
  powerAdd: 0,
  powerMult: 1,
  netClearanceAdd: 0,
  netClearanceMin: null,
  netClearanceMax: null,
  topspinMult: 1,
  backspinMult: 1,
  sidespinMult: 1,
  hitHeightMin: null,
  hitHeightMax: null,
  flightProfile: null,
  tags: Object.freeze([]),
});

export const SHOT_IDENTITIES = Object.freeze({
  [ShotFamily.TOPSPIN]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerMult: 0.98,
    netClearanceAdd: 0.22,
    netClearanceMin: 0.82,
    topspinMult: 1.45,
    sidespinMult: 0.70,
    tags: Object.freeze(['heavy_shape', 'safe_arc']),
  }),
  [ShotFamily.FLAT_DRIVE]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: 3.0,
    powerMult: 1.08,
    netClearanceAdd: -0.22,
    netClearanceMin: 0.34,
    netClearanceMax: 0.82,
    topspinMult: 0.30,
    sidespinMult: 0.25,
    tags: Object.freeze(['low_drive', 'pace']),
  }),
  [ShotFamily.SLICE]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: -3.5,
    powerMult: 0.82,
    netClearanceAdd: -0.10,
    netClearanceMin: 0.32,
    netClearanceMax: 0.78,
    backspinMult: 1.65,
    sidespinMult: 0.55,
    tags: Object.freeze(['skid', 'backspin']),
  }),
  [ShotFamily.LOB]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: -8.0,
    powerMult: 0.70,
    netClearanceAdd: 1.05,
    netClearanceMin: 2.75,
    netClearanceMax: 4.20,
    topspinMult: 0.65,
    sidespinMult: 0.15,
    flightProfile: Object.freeze({
      preferHighArc: true,
      vzMin: 8.2,
      vzMax: 22.0,
      highArcFloor: 11.0,
      maxLandingError: 2.15,
      netMinZ: 2.7,
      solverSpinScale: 1.4,
    }),
    tags: Object.freeze(['high_arc', 'defensive_height']),
  }),
  [ShotFamily.DROP]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: -13.0,
    powerMult: 0.48,
    netClearanceAdd: -0.24,
    netClearanceMin: 0.90,
    netClearanceMax: 1.18,
    backspinMult: 1.80,
    sidespinMult: 0.25,
    flightProfile: Object.freeze({
      mode: 'drop_rewrite',
      minTime: 0.54,
      maxTime: 0.92,
      minSpeed: 4.8,
      maxSpeed: 8.5,
      netMinZ: 1.00,
      strictArc: true,
    }),
    tags: Object.freeze(['touch', 'dead_ball']),
  }),
  [ShotFamily.VOLLEY]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: -1.5,
    powerMult: 0.82,
    netClearanceAdd: -0.18,
    netClearanceMin: 0.24,
    netClearanceMax: 0.68,
    topspinMult: 0.18,
    backspinMult: 0.60,
    sidespinMult: 0.25,
    hitHeightMin: 0.80,
    tags: Object.freeze(['punch', 'short_swing']),
  }),
  [ShotFamily.SMASH]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: 6.0,
    powerMult: 1.18,
    netClearanceAdd: -0.26,
    netClearanceMin: 0.24,
    netClearanceMax: 0.72,
    topspinMult: 0.18,
    sidespinMult: 0.10,
    hitHeightMin: 1.80,
    tags: Object.freeze(['overhead', 'downward_power']),
  }),
  [ShotFamily.BLOCK_RETURN]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: -3.8,
    powerMult: 0.74,
    netClearanceAdd: -0.02,
    netClearanceMin: 0.46,
    netClearanceMax: 0.92,
    topspinMult: 0.35,
    backspinMult: 0.45,
    sidespinMult: 0.15,
    tags: Object.freeze(['absorb', 'redirect']),
  }),
  [ShotFamily.CHIP_RETURN]: Object.freeze({
    ...DEFAULT_IDENTITY,
    powerAdd: -5.6,
    powerMult: 0.66,
    netClearanceAdd: -0.14,
    netClearanceMin: 0.42,
    netClearanceMax: 0.78,
    backspinMult: 1.35,
    sidespinMult: 0.40,
    tags: Object.freeze(['chip', 'backspin_return']),
  }),
});

export function getShotIdentity(family) {
  return SHOT_IDENTITIES[family] ?? DEFAULT_IDENTITY;
}
