import { shotTuningSummary } from './ShotTuning.js';
import { qualityBand } from './ShotQuality.js';

export function buildShotEngineSnapshot({ context, quality, decision, execution } = {}) {
  const caps = context?.capabilities ?? {};
  const memory = context?.memory ?? {};
  return Object.freeze({
    version: 'shot-diagnostics-v1',
    tuning: shotTuningSummary(),
    phase: context?.phase ?? null,
    playerSignature: context?.player?.naturalSignature ?? context?.player?.signatureShot ?? null,
    signatureMove: decision?.signatureMove ?? execution?.signatureMove ?? null,
    family: decision?.family ?? null,
    blueprintId: decision?.blueprintId ?? null,
    blueprintLabel: decision?.blueprintLabel ?? null,
    blueprintTags: decision?.shotBlueprint?.tags ?? [],
    predictedOutcome: decision?.predictedOutcome ?? null,
    intent: decision?.intent ?? null,
    direction: decision?.direction ?? null,
    buildMode: decision?.buildMode ?? null,
    finishMode: decision?.finishMode ?? null,
    returnOutcome: decision?.returnOutcome ?? null,
    returnPlanFamily: decision?.returnPlanFamily ?? null,
    returnPill: decision?.returnPill ?? null,
    serveReturnKind: decision?.serveReturnKind ?? null,
    weakReturnScore: decision?.weakReturnScore ?? null,
    returnMissChance: decision?.returnMissChance ?? null,
    returnPosture: decision?.returnPosture ?? null,
    returnRealEmergency: decision?.returnRealEmergency ?? false,
    returnReactiveReach: decision?.returnReactiveReach ?? null,
    returnContact: decision?.returnContact ?? null,
    styleSubType: decision?.styleSubType ?? decision?.finishProfile?.archetype ?? null,
    tacticalPlan: decision?.tacticalPlan ?? null,
    sliceProfile: decision?.sliceProfile ?? execution?.sliceProfile ?? null,
    touchVariation: context?.player?.ctx?.matchCtx?.touchVariation
      ? { ...context.player.ctx.matchCtx.touchVariation }
      : null,
    opponentTouchAlert: context?.opponent?.ctx?.matchCtx?.touchDefense
      ? { ...context.opponent.ctx.matchCtx.touchDefense }
      : null,
    selectionMode: decision?.selectionMode ?? null,
    candidateScores: decision?.candidateScores ?? [],
    activePattern: decision?.activePattern ?? null,
    patternConfidence: decision?.patternConfidence ?? null,
    opponentReadState: decision?.opponentReadState ?? null,
    opportunityEV: decision?.opportunityEV ?? null,
    courtIdentity: decision?.courtIdentity ?? null,
    coaching: decision?.coaching ?? null,
    tacticalDirection: decision?.tacticalDirection ?? null,
    wrongFoot: decision?.wrongFoot ?? execution?.wrongFoot ?? null,
    quality: quality
      ? {
          value: quality.quality,
          band: qualityBand(quality.quality),
          bodyState: quality.bodyState,
          canContact: quality.canContact,
          scores: quality.scores,
          penalties: quality.penalties,
        }
      : null,
    attributes: {
      wingPower: caps.wingPower ?? null,
      wingControl: caps.wingControl ?? null,
      topspin: caps.topspin ?? null,
      slice: caps.slice ?? null,
      servePower: caps.servePower ?? null,
      servePrecision: caps.servePrecision ?? null,
      return: caps.return ?? null,
      riskTolerance: caps.riskTolerance ?? null,
      errorResistance: caps.errorResistance ?? null,
    },
    memory: {
      rallyPlan: memory.rallyPlan ?? null,
      directionStreak: memory.directionStreak ?? null,
      familyStreak: memory.familyStreak ?? null,
      pressureBuilt: memory.pressureBuilt ?? null,
      pressureFaced: memory.pressureFaced ?? null,
      sliceLoop: memory.sliceLoop ?? null,
      softLoop: memory.softLoop ?? null,
      pointPlan: memory.pointPlan ?? null,
    },
    execution: execution
      ? {
          targetX: execution.targetX,
          targetY: execution.targetY,
          power: execution.power,
          netClearance: execution.netClearance,
          spinType: execution.spinType,
          spinX: execution.actualSpinX,
          spinZ: execution.actualSpinZ,
          errorRisk: execution.errorRisk,
          executionQuality: execution.executionProfile?.executionQuality ?? null,
          technique: execution.executionProfile?.technique ?? null,
          preparation: execution.executionProfile?.preparation ?? null,
          decisionQuality: execution.executionProfile?.decisionQuality ?? null,
          intentDemand: execution.executionProfile?.intentDemand ?? null,
          intentFit: execution.executionProfile?.intentFit ?? null,
          ambitionGap: execution.executionProfile?.ambitionGap ?? null,
          executionMode: execution.executionMode ?? execution.executionProfile?.executionMode ?? null,
          dispersion: execution.dispersion,
          landingEnvelope: execution.landingEnvelope ?? execution.target?.landingEnvelope ?? null,
          wrongFoot: execution.wrongFoot ?? null,
          landingError: execution.landingError ?? null,
          missChance: execution.missChance,
          forcedErrorKind: execution.forcedErrorKind,
          identityTags: execution.identityTags ?? [],
          blueprintId: execution.blueprintId ?? decision?.blueprintId ?? null,
          blueprintLabel: execution.blueprintLabel ?? decision?.blueprintLabel ?? null,
          courtIdentity: decision?.courtIdentity ?? null,
          coaching: decision?.coaching ?? null,
          signatureMove: execution.signatureMove ?? decision?.signatureMove ?? null,
          flightProfileMode: execution.flightProfile?.mode ?? null,
          sliceProfile: execution?.sliceProfile ?? null,
          debugFlags: execution.debugFlags ?? [],
        }
      : null,
  });
}
