/**
 * SponsorProfiles.js — Fase 3: Catálogo de Patrocinadores
 *
 * Elenco permanente do universo: ~70 marcas com personalidade,
 * orçamento, critérios de investimento e comportamento próprio.
 *
 * Cada marca tem:
 *   id, name, category, tier, logo (emoji), tagline
 *   budget               — total disponível por temporada para contratos
 *   minMarketability     — score mínimo para considerar o jogador
 *   preferredStyles[]    — estilos de jogo preferidos
 *   preferredNationality[] — mercados prioritários (ISO-2)
 *   maxContracts         — máximo de contratos ativos simultâneos
 *   riskTolerance        — 0–1: prefere jovens prospects vs veteranos
 *   loyaltyFactor        — 0–1: tende a renovar vs trocar
 *   personality          — arquétipo de marca (afeta narrativa)
 *   conservativeImage    — boolean: rescinde por escândalo?
 *   energyBrand          — boolean: prefere IFR alto sobre tudo
 *   luxuryBrand          — boolean: prefere veteranos campeões
 *   preferredSurface     — superfície favorita (opcional)
 *   description          — texto narrativo (para ChronicleEngine)
 *
 * CATEGORIAS:
 *   RACKET     — raquetes e equipamento de jogo
 *   APPAREL    — roupas e calçados esportivos
 *   LUXURY     — relógios, carros, moda de luxo
 *   FINANCE    — bancos, seguros, fintechs
 *   TECH       — tecnologia, apps, eletrônicos
 *   ENERGY     — bebidas energéticas e nutrição
 *   AUTOMOTIVE — automóveis (não luxo)
 *   AIRLINE    — companhias aéreas
 *   RETAIL     — varejo esportivo e consumo geral
 *   MEDIA      — streaming, mídia e entretenimento
 *   CONSUMER   — alimentação, bebidas, telecom, marketplaces e consumo de massa
 */

// ─────────────────────────────────────────────────────────────────────────────
// ESTILOS DE JOGO (mirror de styles.js — ids usados em preferredStyles)
// ─────────────────────────────────────────────────────────────────────────────
export const STYLE_IDS = {
  AGG_BASELINER:   'AGG_BASELINER',
  DEF_BASELINER:   'DEF_BASELINER',
  SERVE_VOLLEY:    'SERVE_VOLLEY',
  COUNTER_PUNCHER: 'COUNTER_PUNCHER',
  ALL_COURT:       'ALL_COURT',
  POWER_SERVER:    'POWER_SERVER',
  SHOWMAN:         'SHOWMAN',
  GRINDER:         'GRINDER',
};

// ─────────────────────────────────────────────────────────────────────────────
// TIERS — faixas de contrato e requisitos
// ─────────────────────────────────────────────────────────────────────────────
export const SPONSOR_TIERS = {
  ENTRY: {
    id:            'ENTRY',
    label:         'Entry',
    color:         '#8899AA',
    glow:          'rgba(136,153,170,0.20)',
    contractRange: [50_000, 200_000],
    minMarket:     20,
    maxContracts:  999,
    description:   'Marcas regionais e equipamentos locais.',
  },
  MID: {
    id:            'MID',
    label:         'Mid',
    color:         '#60C8FF',
    glow:          'rgba(96,200,255,0.25)',
    contractRange: [200_000, 800_000],
    minMarket:     40,
    maxContracts:  20,
    description:   'Marcas nacionais e equipamentos mid-tier.',
  },
  PREMIUM: {
    id:            'PREMIUM',
    label:         'Premium',
    color:         '#60FF90',
    glow:          'rgba(96,255,144,0.30)',
    contractRange: [800_000, 3_000_000],
    minMarket:     60,
    maxContracts:  8,
    description:   'Nike, Adidas, Babolat — o topo do mainstream.',
  },
  ELITE: {
    id:            'ELITE',
    label:         'Elite',
    color:         '#FFD700',
    glow:          'rgba(255,215,0,0.40)',
    contractRange: [3_000_000, 15_000_000],
    minMarket:     80,
    maxContracts:  3,
    description:   'Rolex, Emirates, Apple — contratos que definem legado.',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// PERSONALIDADES DE MARCA
// ─────────────────────────────────────────────────────────────────────────────
export const BRAND_PERSONALITIES = {
  CHAMPION_HUNTER:   'CHAMPION_HUNTER',   // quer o nº1 / campeão do GS
  REBEL_SEEKER:      'REBEL_SEEKER',      // quer o ousado, o controverso
  HERITAGE:          'HERITAGE',          // quer o elegante, o clássico
  INNOVATION:        'INNOVATION',        // quer o jovem talento, o futuro
  MASS_APPEAL:       'MASS_APPEAL',       // quer o mais popular, mais fãs
  UNDERDOG_PATRON:   'UNDERDOG_PATRON',   // apostador em prospects
  SURFACE_EXPERT:    'SURFACE_EXPERT',    // quer especialistas de superfície
  GLOBAL_REACH:      'GLOBAL_REACH',      // prefere jogadores de mercados grandes
};

// ─────────────────────────────────────────────────────────────────────────────
// CATÁLOGO DE PATROCINADORES
// ─────────────────────────────────────────────────────────────────────────────

export const SPONSOR_CATALOG = [

  // ═══════════════════════════════════════════════════════════════
  // RAQUETES — ELITE / PREMIUM
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'APEX_RACKETS',
    name: 'Apex',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '🎾',
    tagline: 'O jogo começa aqui.',
    budget: 18_000_000,
    minMarketability: 75,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER, STYLE_IDS.SHOWMAN],
    preferredNationality: [],
    maxContracts: 4,
    riskTolerance: 0.3,
    loyaltyFactor: 0.75,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'A maior fabricante de raquetes do mundo. Só quer campeões.',
  },
  {
    id: 'STRATO_SPORTS',
    name: 'Strato',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🎾',
    tagline: 'Precisão. Velocidade. Domínio.',
    budget: 8_000_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.GRINDER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.5,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Aposta em jogadores consistentes e de alta durabilidade de carreira.',
  },
  {
    id: 'VOLT_FRAME',
    name: 'Volt',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '⚡',
    tagline: 'Mais potência. Menos limites.',
    budget: 6_500_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'AU', 'DE'],
    maxContracts: 8,
    riskTolerance: 0.6,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca americana que aposta em jovens agressivos.',
  },
  {
    id: 'TIERRA_RACKETS',
    name: 'Tierra',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🧱',
    tagline: 'Feito para saibro. Feito para durar.',
    budget: 5_000_000,
    minMarketability: 45,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['ES', 'AR', 'FR', 'IT'],
    maxContracts: 10,
    riskTolerance: 0.5,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.SURFACE_EXPERT,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    preferredSurface: 'CLAY',
    description: 'Marca espanhola especialista em saibro. Lealdade extrema aos seus atletas.',
  },
  {
    id: 'GREENLINE_RACKETS',
    name: 'Greenline',
    category: 'RACKET',
    tier: 'MID',
    logo: '🌿',
    tagline: 'Sustentável. Competitivo.',
    budget: 2_500_000,
    minMarketability: 35,
    preferredStyles: [],
    preferredNationality: ['GB', 'AU', 'NZ', 'SE'],
    maxContracts: 15,
    riskTolerance: 0.55,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca britânica com foco em sustentabilidade e mercados anglófonos.',
  },
  {
    id: 'NOVA_RACKETS',
    name: 'Nova',
    category: 'RACKET',
    tier: 'MID',
    logo: '🌟',
    tagline: 'O próximo nível.',
    budget: 1_800_000,
    minMarketability: 30,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 20,
    riskTolerance: 0.75,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Especialista em revelar talentos. Aposta alto em prospects.',
  },

  // ═══════════════════════════════════════════════════════════════
  // APPAREL — ELITE / PREMIUM
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'NEON_SPORTS',
    name: 'Neon',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '👟',
    tagline: 'Vista a vitória.',
    budget: 22_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'BR', 'FR', 'JP'],
    maxContracts: 3,
    riskTolerance: 0.2,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'O maior contrato de vestuário do circuito. Exige campeões e carisma.',
  },
  {
    id: 'CREST_APPAREL',
    name: 'Crest',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '👔',
    tagline: 'Elegância em movimento.',
    budget: 16_000_000,
    minMarketability: 75,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.SHOWMAN],
    preferredNationality: ['GB', 'SE', 'CH', 'AT'],
    maxContracts: 3,
    riskTolerance: 0.15,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca britânica clássica. Quer elegância e títulos em Wimbledon.',
  },
  {
    id: 'STRIKER_WEAR',
    name: 'Striker',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '⚔️',
    tagline: 'Feito para atacar.',
    budget: 9_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'AU', 'CA'],
    maxContracts: 8,
    riskTolerance: 0.55,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Americana agressiva. Gosta de jogadores que dominam pelo poder.',
  },
  {
    id: 'ARENA_SPORT',
    name: 'Arena',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '🏟️',
    tagline: 'Cada quadra. Cada clima.',
    budget: 7_500_000,
    minMarketability: 52,
    preferredStyles: [],
    preferredNationality: ['IT', 'FR', 'ES', 'PT'],
    maxContracts: 8,
    riskTolerance: 0.45,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Italiana com forte presença no circuito europeu de saibro.',
  },
  {
    id: 'RUSH_ATHLETIC',
    name: 'Rush',
    category: 'APPAREL',
    tier: 'MID',
    logo: '💨',
    tagline: 'Mais rápido. Mais forte.',
    budget: 2_200_000,
    minMarketability: 38,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.GRINDER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.65,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Aposta em defensores e jogadores de alta resistência.',
  },

  // ═══════════════════════════════════════════════════════════════
  // LUXURY
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'MERIDIAN_WATCHES',
    name: 'Meridian',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '⌚',
    tagline: 'O tempo pertence aos campeões.',
    budget: 20_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['CH', 'DE', 'AT', 'GB'],
    maxContracts: 3,
    riskTolerance: 0.05,
    loyaltyFactor: 0.95,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Relojoaria suíça. Quer apenas campeões estabelecidos. Lealdade absoluta.',
  },
  {
    id: 'AURUM_MOTORS',
    name: 'Aurum',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '🚗',
    tagline: 'A excelência move o mundo.',
    budget: 15_000_000,
    minMarketability: 78,
    preferredStyles: [],
    preferredNationality: ['DE', 'GB', 'US', 'JP', 'KR'],
    maxContracts: 3,
    riskTolerance: 0.10,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Montadora de luxo alemã. Exige imagem impecável e alcance global.',
  },
  {
    id: 'CIEL_FASHION',
    name: 'Ciel',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '👑',
    tagline: 'Além do esporte.',
    budget: 12_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['FR', 'IT', 'ES'],
    maxContracts: 3,
    riskTolerance: 0.08,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Alta moda francesa. Quer o jogador-ícone que transcende o esporte.',
  },
  {
    id: 'ONYX_PRESTIGE',
    name: 'Onyx',
    category: 'LUXURY',
    tier: 'PREMIUM',
    logo: '💎',
    tagline: 'Para quem exige o melhor.',
    budget: 4_500_000,
    minMarketability: 65,
    preferredStyles: [],
    preferredNationality: ['AE', 'CN', 'RU', 'SA'],
    maxContracts: 6,
    riskTolerance: 0.20,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca premium dos Emirados. Foco em mercados de alto crescimento.',
  },

  // ═══════════════════════════════════════════════════════════════
  // TECHNOLOGY
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'NEXUS_TECH',
    name: 'Nexus',
    category: 'TECH',
    tier: 'ELITE',
    logo: '📱',
    tagline: 'Conecte-se ao futuro.',
    budget: 25_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'JP', 'KR', 'CN', 'IN'],
    maxContracts: 3,
    riskTolerance: 0.35,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante de tecnologia. Quer o rosto do esporte conectado.',
  },
  {
    id: 'PULSE_WEARABLES',
    name: 'Pulse',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '⌚',
    tagline: 'Monitore cada batalha.',
    budget: 5_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.60,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Wearables esportivos. Prefere jogadores com narrativa de performance.',
  },
  {
    id: 'CODEC_STREAMING',
    name: 'Codec',
    category: 'MEDIA',
    tier: 'PREMIUM',
    logo: '📺',
    tagline: 'Todo ponto. Ao vivo.',
    budget: 6_000_000,
    minMarketability: 60,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'BR', 'MX'],
    maxContracts: 6,
    riskTolerance: 0.45,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Plataforma de streaming de esportes. Quer faces reconhecíveis.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENERGY / NUTRITION
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'VOLT_ENERGY',
    name: 'Volt Energy',
    category: 'ENERGY',
    tier: 'PREMIUM',
    logo: '⚡',
    tagline: 'Energia sem limites.',
    budget: 7_000_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'AU', 'DE', 'BR'],
    maxContracts: 7,
    riskTolerance: 0.80,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Bebida energética. Prefere jovens com IFR alto e atitude. Baixa lealdade.',
  },
  {
    id: 'APEX_NUTRITION',
    name: 'Apex Nutrition',
    category: 'ENERGY',
    tier: 'PREMIUM',
    logo: '💪',
    tagline: 'Performance de elite.',
    budget: 5_000_000,
    minMarketability: 48,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.65,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Suplementos. Gosta de jogadores que simbolizam disciplina e resistência.',
  },
  {
    id: 'STORM_DRINKS',
    name: 'Storm',
    category: 'ENERGY',
    tier: 'MID',
    logo: '🌩️',
    tagline: 'Libera a tempestade.',
    budget: 1_800_000,
    minMarketability: 32,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: [],
    maxContracts: 15,
    riskTolerance: 0.85,
    loyaltyFactor: 0.25,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Marca jovem. Aposta agressiva em prospects com potencial explosivo.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AIRLINES
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ALTITUDE_AIRLINES',
    name: 'Altitude Airlines',
    category: 'AIRLINE',
    tier: 'ELITE',
    logo: '✈️',
    tagline: 'O mundo é a sua quadra.',
    budget: 18_000_000,
    minMarketability: 76,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 3,
    riskTolerance: 0.10,
    loyaltyFactor: 0.75,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea premium. Quer um embaixador global reconhecível.',
  },
  {
    id: 'SKYPATH_AIRLINES',
    name: 'SkyPath',
    category: 'AIRLINE',
    tier: 'PREMIUM',
    logo: '🛫',
    tagline: 'Conectando campeões.',
    budget: 4_000_000,
    minMarketability: 58,
    preferredStyles: [],
    preferredNationality: ['BR', 'AR', 'CL', 'CO', 'MX'],
    maxContracts: 6,
    riskTolerance: 0.40,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia sul-americana. Prioriza jogadores do continente.',
  },

  // ═══════════════════════════════════════════════════════════════
  // FINANCE
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'CAPITAL_BANK',
    name: 'Capital',
    category: 'FINANCE',
    tier: 'ELITE',
    logo: '🏦',
    tagline: 'Invista no que importa.',
    budget: 14_000_000,
    minMarketability: 78,
    preferredStyles: [],
    preferredNationality: ['US', 'GB', 'JP', 'AU'],
    maxContracts: 3,
    riskTolerance: 0.08,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco global. Imagem conservadora absoluta. Lealdade extrema.',
  },
  {
    id: 'ZENITH_FINTECH',
    name: 'Zenith',
    category: 'FINANCE',
    tier: 'PREMIUM',
    logo: '💳',
    tagline: 'O dinheiro do futuro.',
    budget: 6_000_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'IN', 'CN', 'BR'],
    maxContracts: 6,
    riskTolerance: 0.50,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fintech disruptiva. Quer o jogador que representa a nova geração.',
  },
  {
    id: 'FORTIS_INSURANCE',
    name: 'Fortis',
    category: 'FINANCE',
    tier: 'MID',
    logo: '🛡️',
    tagline: 'Proteja o que importa.',
    budget: 1_500_000,
    minMarketability: 38,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.GRINDER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.20,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Seguradora europeia. Prefere defensores — a metáfora é óbvia.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AUTOMOTIVE (não luxo)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'TORQUE_MOTORS',
    name: 'Torque',
    category: 'AUTOMOTIVE',
    tier: 'PREMIUM',
    logo: '🏎️',
    tagline: 'Da linha de saída à vitória.',
    budget: 8_000_000,
    minMarketability: 60,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'DE', 'AU'],
    maxContracts: 6,
    riskTolerance: 0.40,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora americana de performance. Gosta de jogadores agressivos.',
  },
  {
    id: 'VERDE_EV',
    name: 'Verde',
    category: 'AUTOMOTIVE',
    tier: 'MID',
    logo: '🔋',
    tagline: 'O futuro, sem emissões.',
    budget: 2_000_000,
    minMarketability: 42,
    preferredStyles: [],
    preferredNationality: ['DE', 'NL', 'SE', 'NO'],
    maxContracts: 14,
    riskTolerance: 0.55,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora europeia de elétricos. Prefere atletas com imagem sustentável.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RETAIL
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'SPORT_ZONE',
    name: 'Sport Zone',
    category: 'RETAIL',
    tier: 'MID',
    logo: '🏪',
    tagline: 'Tudo para o seu esporte.',
    budget: 2_800_000,
    minMarketability: 35,
    preferredStyles: [],
    preferredNationality: ['BR', 'PT', 'ES', 'MX'],
    maxContracts: 20,
    riskTolerance: 0.45,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Varejista esportiva lusófona. Ampla base de contratos, valores modestos.',
  },
  {
    id: 'COURT_KING_RETAIL',
    name: 'Court King',
    category: 'RETAIL',
    tier: 'ENTRY',
    logo: '👑',
    tagline: 'O rei começa aqui.',
    budget: 800_000,
    minMarketability: 20,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.90,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Varejista online de materiais de tênis. Porta de entrada para prospects.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENTRY — complementos regionais
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ALPHA_STRING_CO',
    name: 'Alpha Strings',
    category: 'RACKET',
    tier: 'ENTRY',
    logo: '🎵',
    tagline: 'A tensão certa para cada jogo.',
    budget: 500_000,
    minMarketability: 18,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.85,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fabricante de cordas. Primeira marca a apostar em prospects desconhecidos.',
  },
  {
    id: 'HYDRO_SPORTS_DRINK',
    name: 'Hydro',
    category: 'ENERGY',
    tier: 'ENTRY',
    logo: '💧',
    tagline: 'Hidrate-se. Vença.',
    budget: 600_000,
    minMarketability: 22,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.70,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Bebida isotônica entry-level. Principal parceiro de jovens no circuito.',
  },
  {
    id: 'BASELINE_APPAREL',
    name: 'Baseline',
    category: 'APPAREL',
    tier: 'ENTRY',
    logo: '👕',
    tagline: 'Começando pelo começo.',
    budget: 700_000,
    minMarketability: 18,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.80,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Roupa esportiva entry. Veste qualquer jogador disposto a usar o logo.',
  },
  {
    id: 'REGIONAL_BANK_EU',
    name: 'EuroBanca',
    category: 'FINANCE',
    tier: 'ENTRY',
    logo: '🏛️',
    tagline: 'Próxima de você.',
    budget: 400_000,
    minMarketability: 20,
    preferredStyles: [],
    preferredNationality: ['IT', 'FR', 'ES', 'PT', 'GR'],
    maxContracts: 999,
    riskTolerance: 0.30,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco regional europeu. Apoia atletas locais com contratos pequenos e duradouros.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RACKET — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'KRONOS_RACKETS',
    name: 'Kronos',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '⚙️',
    tagline: 'Engenharia sem concessões.',
    budget: 14_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['DE', 'AT', 'CH', 'CZ'],
    maxContracts: 3,
    riskTolerance: 0.25,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca alemã de engenharia de precisão. Prefere jogadores completos e duradouros.',
  },
  {
    id: 'FALCON_RACKETS',
    name: 'Falcon',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🦅',
    tagline: 'Velocidade no primeiro serviço.',
    budget: 7_500_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['US', 'AU', 'CA'],
    maxContracts: 7,
    riskTolerance: 0.55,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca americana especializada em jogadores de serviço dominante.',
  },
  {
    id: 'KAZE_RACKETS',
    name: 'Kaze',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🌊',
    tagline: 'Leveza que corta o vento.',
    budget: 5_500_000,
    minMarketability: 45,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['JP', 'KR', 'CN', 'TW'],
    maxContracts: 10,
    riskTolerance: 0.45,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.SURFACE_EXPERT,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca japonesa de alta precisão. Leal aos seus atletas asiáticos.',
  },
  {
    id: 'REDLINE_RACKETS',
    name: 'Redline',
    category: 'RACKET',
    tier: 'MID',
    logo: '🔴',
    tagline: 'No limite. Sempre.',
    budget: 2_000_000,
    minMarketability: 32,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.70,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca jovem que busca personagens agressivos e controversos.',
  },
  {
    id: 'SWIFT_RACKETS',
    name: 'Swift',
    category: 'RACKET',
    tier: 'MID',
    logo: '💨',
    tagline: 'Reação em milissegundos.',
    budget: 1_600_000,
    minMarketability: 28,
    preferredStyles: [STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['GB', 'IE', 'AU'],
    maxContracts: 20,
    riskTolerance: 0.60,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Aposta em jogadores de net e contra-atacantes em desenvolvimento.',
  },
  {
    id: 'OPEN_COURT_RACKETS',
    name: 'Open Court',
    category: 'RACKET',
    tier: 'ENTRY',
    logo: '🎾',
    tagline: 'Para quem começa a jogar sério.',
    budget: 500_000,
    minMarketability: 18,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.80,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fabricante de entrada que aposta em prospects sem nome.',
  },

  // ═══════════════════════════════════════════════════════════════
  // APPAREL — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'VICTOIRE_APPAREL',
    name: 'Victoire',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '🏅',
    tagline: 'A elegância como vantagem.',
    budget: 20_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.SHOWMAN],
    preferredNationality: ['FR', 'IT', 'ES', 'BE'],
    maxContracts: 3,
    riskTolerance: 0.20,
    loyaltyFactor: 0.90,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca francesa de vestuário esportivo de luxo. Quer campeões com elegância.',
  },
  {
    id: 'KINETIC_APPAREL',
    name: 'Kinetic',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '⚡',
    tagline: 'Movimento sem atrito.',
    budget: 8_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Foco em tecnologia de tecido e performance extrema. Adora jovens talentos.',
  },
  {
    id: 'VALOR_APPAREL',
    name: 'Valor',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '🛡️',
    tagline: 'Veste quem não desiste.',
    budget: 6_500_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['BR', 'AR', 'CO', 'CL'],
    maxContracts: 9,
    riskTolerance: 0.55,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca latino-americana que celebra resiliência e guerreiros da quadra.',
  },
  {
    id: 'SPRINT_WEAR',
    name: 'Sprint',
    category: 'APPAREL',
    tier: 'MID',
    logo: '🏃',
    tagline: 'Cada ponto, um sprint.',
    budget: 2_000_000,
    minMarketability: 30,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.65,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca de volume que quer atletas populares e acessíveis ao público.',
  },
  {
    id: 'COAST_ATHLETIC',
    name: 'Coast',
    category: 'APPAREL',
    tier: 'MID',
    logo: '🌊',
    tagline: 'Do court para a praia.',
    budget: 1_700_000,
    minMarketability: 28,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['AU', 'US', 'BR', 'ZA'],
    maxContracts: 20,
    riskTolerance: 0.70,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Estilo descontraído de países costeiros. Prefere personalidades fortes.',
  },
  {
    id: 'MATCH_POINT_APPAREL',
    name: 'Match Point',
    category: 'APPAREL',
    tier: 'ENTRY',
    logo: '🎽',
    tagline: 'Pronto para jogar.',
    budget: 350_000,
    minMarketability: 15,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.85,
    loyaltyFactor: 0.25,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Vestuário de entrada. Financia qualquer atleta promissor.',
  },

  // ═══════════════════════════════════════════════════════════════
  // LUXURY — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'LUMIERE_JEWELS',
    name: 'Lumière',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '💎',
    tagline: 'Brilho que transcende o jogo.',
    budget: 17_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['FR', 'IT', 'CH', 'GB'],
    maxContracts: 2,
    riskTolerance: 0.15,
    loyaltyFactor: 0.95,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Joalheria francesa de alta costura. Quer apenas ícones sem escândalos.',
  },
  {
    id: 'OBSIDIAN_SPIRITS',
    name: 'Obsidian',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '🥃',
    tagline: 'Para os que sabem o que querem.',
    budget: 13_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['GB', 'IE', 'US', 'JP'],
    maxContracts: 3,
    riskTolerance: 0.30,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca de whisky de luxo. Quer o campeão mais elegante do circuito.',
  },
  {
    id: 'ARGENT_LUXURY',
    name: 'Argent',
    category: 'LUXURY',
    tier: 'PREMIUM',
    logo: '🥈',
    tagline: 'Quase o topo. E com estilo.',
    budget: 4_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: [],
    maxContracts: 6,
    riskTolerance: 0.40,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Joia premium acessível. Quer jogadores populares com boa imagem.',
  },

  // ═══════════════════════════════════════════════════════════════
  // TECH — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'SYNAPSE_TECH',
    name: 'Synapse',
    category: 'TECH',
    tier: 'ELITE',
    logo: '🧠',
    tagline: 'A inteligência do jogo.',
    budget: 28_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 4,
    riskTolerance: 0.35,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante global de IA e tecnologia. O maior budget do circuito.',
  },
  {
    id: 'ORBIT_STREAMING',
    name: 'Orbit',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '📡',
    tagline: 'Transmitindo cada momento.',
    budget: 7_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.55,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Plataforma de streaming esportivo. Quer atletas que geram audiência.',
  },
  {
    id: 'WAVE_WEARABLES',
    name: 'Wave',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '⌚',
    tagline: 'Mede tudo. Supera tudo.',
    budget: 5_000_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: [],
    maxContracts: 10,
    riskTolerance: 0.60,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Wearables de performance. Adora prospects com alto potencial técnico.',
  },
  {
    id: 'MESH_GAMING',
    name: 'Mesh',
    category: 'TECH',
    tier: 'MID',
    logo: '🎮',
    tagline: 'Joga no digital. Domina no court.',
    budget: 1_800_000,
    minMarketability: 30,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['KR', 'CN', 'JP', 'US'],
    maxContracts: 15,
    riskTolerance: 0.75,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gaming crossover. Quer atletas jovens e com presença em redes sociais.',
  },

  // ═══════════════════════════════════════════════════════════════
  // MEDIA — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'NETPLAY_MEDIA',
    name: 'NetPlay',
    category: 'MEDIA',
    tier: 'PREMIUM',
    logo: '📺',
    tagline: 'O tênis que o mundo quer ver.',
    budget: 5_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Canal esportivo global. Prefere atletas que geram debate e audiência.',
  },
  {
    id: 'RALLY_TV',
    name: 'Rally TV',
    category: 'MEDIA',
    tier: 'MID',
    logo: '📻',
    tagline: 'Ponto por ponto.',
    budget: 1_500_000,
    minMarketability: 28,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 20,
    riskTolerance: 0.65,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Emissora regional esportiva. Adora revelar novos talentos para o público.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENERGY — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'PRIME_ENERGY',
    name: 'Prime',
    category: 'ENERGY',
    tier: 'ELITE',
    logo: '🔋',
    tagline: 'Energia no nível máximo.',
    budget: 19_000_000,
    minMarketability: 75,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.SHOWMAN, STYLE_IDS.POWER_SERVER],
    preferredNationality: [],
    maxContracts: 4,
    riskTolerance: 0.45,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Maior marca de energia do circuito. Quer os mais intensos e vencedores.',
  },
  {
    id: 'SURGE_ENERGY',
    name: 'Surge',
    category: 'ENERGY',
    tier: 'MID',
    logo: '⚡',
    tagline: 'Mais explosão, menos desculpa.',
    budget: 1_600_000,
    minMarketability: 28,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.72,
    loyaltyFactor: 0.38,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Bebida energética rebelde. Busca atletas com atitude.',
  },
  {
    id: 'CARBO_NUTRITION',
    name: 'Carbo',
    category: 'ENERGY',
    tier: 'ENTRY',
    logo: '🥤',
    tagline: 'Combustível para cada treino.',
    budget: 350_000,
    minMarketability: 15,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.85,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Suplemento de entrada. Assina qualquer atleta disposto a divulgar.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AIRLINE — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'HORIZON_AIRLINES',
    name: 'Horizon Global',
    category: 'AIRLINE',
    tier: 'ELITE',
    logo: '✈️',
    tagline: 'Conectando campeões ao mundo.',
    budget: 22_000_000,
    minMarketability: 78,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 3,
    riskTolerance: 0.20,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea global premium. Quer embaixadores com alcance mundial.',
  },
  {
    id: 'PACIFIC_WINGS',
    name: 'Pacific Wings',
    category: 'AIRLINE',
    tier: 'PREMIUM',
    logo: '🛫',
    tagline: 'Voe com os melhores.',
    budget: 4_500_000,
    minMarketability: 50,
    preferredStyles: [],
    preferredNationality: ['AU', 'JP', 'CN', 'KR', 'NZ'],
    maxContracts: 7,
    riskTolerance: 0.40,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea do Pacífico. Foco em atletas da região Ásia-Pacífico.',
  },

  // ═══════════════════════════════════════════════════════════════
  // FINANCE — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ATLAS_CAPITAL',
    name: 'Atlas Capital',
    category: 'FINANCE',
    tier: 'ELITE',
    logo: '🌐',
    tagline: 'O peso do mundo. A força dos seus investimentos.',
    budget: 16_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: [],
    maxContracts: 3,
    riskTolerance: 0.25,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fundo de investimento global. Quer associar sua marca a campeões estáveis.',
  },
  {
    id: 'STERLING_BANK',
    name: 'Sterling',
    category: 'FINANCE',
    tier: 'PREMIUM',
    logo: '💷',
    tagline: 'Patrimônio construído com consistência.',
    budget: 5_000_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.GRINDER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['GB', 'IE', 'AU', 'NZ', 'CA'],
    maxContracts: 8,
    riskTolerance: 0.30,
    loyaltyFactor: 0.75,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco britânico tradicional. Valoriza atletas consistentes e de longa carreira.',
  },
  {
    id: 'COMET_CREDIT',
    name: 'Comet',
    category: 'FINANCE',
    tier: 'MID',
    logo: '☄️',
    tagline: 'Rápido como você.',
    budget: 1_400_000,
    minMarketability: 25,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 25,
    riskTolerance: 0.65,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fintech de cartões digitais. Quer associação com velocidade e modernidade.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AUTOMOTIVE — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'VELOCE_MOTORS',
    name: 'Veloce',
    category: 'AUTOMOTIVE',
    tier: 'ELITE',
    logo: '🏎️',
    tagline: 'A performance que define o sucesso.',
    budget: 16_500_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['IT', 'DE', 'GB', 'FR'],
    maxContracts: 3,
    riskTolerance: 0.35,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Montadora italiana de supercars. Quer os maiores nomes do circuito.',
  },
  {
    id: 'DRIFT_MOTORS',
    name: 'Drift',
    category: 'AUTOMOTIVE',
    tier: 'PREMIUM',
    logo: '🚗',
    tagline: 'Controle na curva. Domínio na reta.',
    budget: 5_500_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['DE', 'JP', 'KR'],
    maxContracts: 7,
    riskTolerance: 0.45,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora asiático-europeia que quer atletas técnicos e precisos.',
  },
  {
    id: 'URBAN_DRIVE',
    name: 'Urban Drive',
    category: 'AUTOMOTIVE',
    tier: 'MID',
    logo: '🚙',
    tagline: 'Da cidade à vitória.',
    budget: 1_500_000,
    minMarketability: 25,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 20,
    riskTolerance: 0.60,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora urbana acessível. Quer popularidade e volume de público.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RETAIL — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'CHAMPIONS_DEN',
    name: "Champion's Den",
    category: 'RETAIL',
    tier: 'PREMIUM',
    logo: '🏆',
    tagline: 'O esporte dos campeões. Ao seu alcance.',
    budget: 4_500_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.SHOWMAN],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Cadeia premium de artigos esportivos. Quer campeões como rosto da marca.',
  },
  {
    id: 'GAME_ON_RETAIL',
    name: 'Game On',
    category: 'RETAIL',
    tier: 'MID',
    logo: '🛒',
    tagline: 'Equipado para vencer.',
    budget: 1_300_000,
    minMarketability: 22,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 25,
    riskTolerance: 0.70,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Rede de lojas de artigos esportivos com foco em volume e visibilidade.',
  },
  {
    id: 'PARK_TENNIS',
    name: 'Park Tennis',
    category: 'RETAIL',
    tier: 'ENTRY',
    logo: '🌳',
    tagline: 'Comece onde quiser.',
    budget: 280_000,
    minMarketability: 12,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.90,
    loyaltyFactor: 0.20,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Loja de entry-level. Assina qualquer jogador com ranking e visibilidade mínimos.',
  },

  // ═══════════════════════════════════════════════════════════════
  // PATCH 0 — MARCAS GLOBAIS REAIS / MEGA CORPORAÇÕES
  // Garoto-propaganda, campanhas de massa e contratos que atravessam
  // esporte, lifestyle, consumo, tecnologia e reputação pública.
  // ═══════════════════════════════════════════════════════════════

  // SPORTSWEAR / EQUIPMENT — reais
  {
    id: 'NIKE_GLOBAL',
    name: 'Nike',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '👟',
    tagline: 'Just play beyond limits.',
    budget: 35_000_000,
    minMarketability: 84,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'BR', 'FR', 'JP', 'CN'],
    maxContracts: 3,
    riskTolerance: 0.32,
    loyaltyFactor: 0.72,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante global de material esportivo. Quer campeões com carisma mundial e campanhas de impacto.',
  },
  {
    id: 'ADIDAS_GLOBAL',
    name: 'Adidas',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '🎽',
    tagline: 'Impossible is a starting line.',
    budget: 31_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER, STYLE_IDS.SHOWMAN],
    preferredNationality: ['DE', 'GB', 'ES', 'AR', 'BR'],
    maxContracts: 4,
    riskTolerance: 0.35,
    loyaltyFactor: 0.78,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Potência esportiva europeia. Valoriza alcance internacional, consistência e imagem aspiracional.',
  },
  {
    id: 'PUMA_GLOBAL',
    name: 'Puma',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '🐆',
    tagline: 'Fast looks different.',
    budget: 12_000_000,
    minMarketability: 60,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['DE', 'FR', 'IT', 'BR', 'US'],
    maxContracts: 7,
    riskTolerance: 0.58,
    loyaltyFactor: 0.52,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca esportiva agressiva e urbana. Procura atletas com presença, velocidade e atitude.',
  },
  {
    id: 'ASICS_TENNIS',
    name: 'Asics',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '👟',
    tagline: 'Sound mind. Sound body. Sound game.',
    budget: 9_000_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.GRINDER],
    preferredNationality: ['JP', 'AU', 'FR', 'ES'],
    maxContracts: 9,
    riskTolerance: 0.42,
    loyaltyFactor: 0.74,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Especialista em performance e durabilidade. Gosta de jogadores técnicos e fisicamente confiáveis.',
  },
  {
    id: 'WILSON_TENNIS',
    name: 'Wilson',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '🎾',
    tagline: 'Feel the point before it happens.',
    budget: 24_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'GB', 'CH', 'CA'],
    maxContracts: 4,
    riskTolerance: 0.28,
    loyaltyFactor: 0.88,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca lendária de raquetes. Quer atletas com técnica limpa, legado e aura clássica.',
  },
  {
    id: 'BABOLAT_TENNIS',
    name: 'Babolat',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '🎾',
    tagline: 'Spin is a weapon.',
    budget: 21_000_000,
    minMarketability: 74,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.GRINDER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['FR', 'ES', 'AR', 'IT', 'BR'],
    maxContracts: 5,
    riskTolerance: 0.46,
    loyaltyFactor: 0.82,
    personality: BRAND_PERSONALITIES.SURFACE_EXPERT,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    preferredSurface: 'CLAY',
    description: 'Casa dos jogadores de spin pesado. Especialmente agressiva em saibro e mercados latinos.',
  },
  {
    id: 'HEAD_TENNIS',
    name: 'HEAD',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '🎾',
    tagline: 'Precision under pressure.',
    budget: 22_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['AT', 'DE', 'RS', 'HR', 'US'],
    maxContracts: 5,
    riskTolerance: 0.38,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca técnica e competitiva. Procura jogadores de elite que vendem controle, precisão e mentalidade.',
  },
  {
    id: 'YONEX_TENNIS',
    name: 'Yonex',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🏸',
    tagline: 'Geometry wins rallies.',
    budget: 11_000_000,
    minMarketability: 56,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['JP', 'KR', 'CN', 'AU'],
    maxContracts: 8,
    riskTolerance: 0.55,
    loyaltyFactor: 0.76,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca japonesa de engenharia esportiva. Aposta em técnica, precisão e expansão asiática.',
  },

  // FINANCE / INVESTIMENTOS — reais e mega bancos
  {
    id: 'XP_INVESTIMENTOS',
    name: 'XP Investimentos',
    category: 'FINANCE',
    tier: 'PREMIUM',
    logo: '📈',
    tagline: 'Invista no próximo campeão.',
    budget: 8_500_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['BR', 'PT'],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.58,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Plataforma brasileira de investimentos. Quer atletas com apelo nacional, ascensão social e imagem de ambição.',
  },
  {
    id: 'ITAU_PRIVATE',
    name: 'Itaú',
    category: 'FINANCE',
    tier: 'ELITE',
    logo: '🏦',
    tagline: 'Feito de futuro.',
    budget: 18_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['BR'],
    maxContracts: 3,
    riskTolerance: 0.22,
    loyaltyFactor: 0.82,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco brasileiro de grande porte. Valoriza estabilidade, imagem limpa e presença nacional forte.',
  },
  {
    id: 'NUBANK_GLOBAL',
    name: 'Nubank',
    category: 'FINANCE',
    tier: 'PREMIUM',
    logo: '💳',
    tagline: 'O futuro no seu controle.',
    budget: 10_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['BR', 'MX', 'CO'],
    maxContracts: 8,
    riskTolerance: 0.66,
    loyaltyFactor: 0.46,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fintech latina com apelo jovem. Procura atletas modernos, comunicativos e digitais.',
  },
  {
    id: 'JPMORGAN_CHASE',
    name: 'JPMorgan Chase',
    category: 'FINANCE',
    tier: 'ELITE',
    logo: '🏛️',
    tagline: 'Legacy is capital.',
    budget: 24_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['US', 'GB', 'CH', 'DE'],
    maxContracts: 3,
    riskTolerance: 0.16,
    loyaltyFactor: 0.86,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco global de elite. Só entra pesado em atletas estáveis, campeões e institucionalmente seguros.',
  },

  // CONSUMER / FOOD / MASS MARKET
  {
    id: 'MCDONALDS_GLOBAL',
    name: "McDonald's",
    category: 'CONSUMER',
    tier: 'ELITE',
    logo: '🍟',
    tagline: 'Millions watched. Millions smiled.',
    budget: 28_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'BR', 'FR', 'JP', 'MX'],
    maxContracts: 4,
    riskTolerance: 0.42,
    loyaltyFactor: 0.56,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Mega marca global de alimentação. Quer rostos reconhecíveis, carisma popular e alcance familiar.',
  },
  {
    id: 'COCA_COLA_GLOBAL',
    name: 'Coca-Cola',
    category: 'CONSUMER',
    tier: 'ELITE',
    logo: '🥤',
    tagline: 'Open the moment.',
    budget: 30_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['US', 'BR', 'MX', 'JP', 'GB'],
    maxContracts: 3,
    riskTolerance: 0.24,
    loyaltyFactor: 0.72,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Uma das marcas mais reconhecidas do mundo. Compra alcance global, simpatia e baixa volatilidade pública.',
  },
  {
    id: 'PEPSI_GLOBAL',
    name: 'Pepsi',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '🥤',
    tagline: 'New generation. New game.',
    budget: 16_000_000,
    minMarketability: 66,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'MX', 'BR', 'AR'],
    maxContracts: 6,
    riskTolerance: 0.58,
    loyaltyFactor: 0.46,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca de consumo pop. Prefere atletas jovens, barulhentos, carismáticos e culturalmente relevantes.',
  },
  {
    id: 'BURGER_KING_GLOBAL',
    name: 'Burger King',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '🍔',
    tagline: 'Have it your way, win it your way.',
    budget: 9_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'BR', 'ES', 'GB'],
    maxContracts: 8,
    riskTolerance: 0.70,
    loyaltyFactor: 0.38,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Rede global de fast food com tom provocador. Entra bem em atletas irreverentes e campanhas virais.',
  },
  {
    id: 'STARBUCKS_GLOBAL',
    name: 'Starbucks',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '☕',
    tagline: 'Before the match, after the memory.',
    budget: 8_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['US', 'CA', 'GB', 'JP', 'KR'],
    maxContracts: 7,
    riskTolerance: 0.34,
    loyaltyFactor: 0.62,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca global de café e lifestyle urbano. Prefere atletas acessíveis, cosmopolitas e de imagem tranquila.',
  },
  {
    id: 'NESTLE_GLOBAL',
    name: 'Nestlé',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '🍫',
    tagline: 'Growing champions, one habit at a time.',
    budget: 12_500_000,
    minMarketability: 62,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['CH', 'BR', 'FR', 'MX', 'JP'],
    maxContracts: 7,
    riskTolerance: 0.26,
    loyaltyFactor: 0.68,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Conglomerado global de alimentos. Valoriza imagem familiar, segurança e campanhas de grande escala.',
  },
  {
    id: 'AMBEV_BEVERAGES',
    name: 'Ambev',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '🍺',
    tagline: 'Celebre o ponto que muda tudo.',
    budget: 9_000_000,
    minMarketability: 56,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['BR', 'AR', 'UY', 'PY'],
    maxContracts: 8,
    riskTolerance: 0.54,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante de bebidas da América Latina. Compra identificação popular e presença em grandes eventos.',
  },
  {
    id: 'HEINEKEN_GLOBAL',
    name: 'Heineken',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '🍺',
    tagline: 'The taste of big nights.',
    budget: 11_000_000,
    minMarketability: 64,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['NL', 'GB', 'BR', 'ES', 'US'],
    maxContracts: 6,
    riskTolerance: 0.42,
    loyaltyFactor: 0.58,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca global de cerveja premium. Quer jogadores adultos, globais e conectados a grandes noites esportivas.',
  },

  // TECH / TELECOM / MARKETPLACES — reais
  {
    id: 'APPLE_GLOBAL',
    name: 'Apple',
    category: 'TECH',
    tier: 'ELITE',
    logo: '📱',
    tagline: 'Designed for greatness.',
    budget: 42_000_000,
    minMarketability: 86,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'JP', 'GB', 'CN', 'DE'],
    maxContracts: 2,
    riskTolerance: 0.14,
    loyaltyFactor: 0.82,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca tecnológica de prestígio absoluto. Só quer ícones limpos, globais e culturalmente aspiracionais.',
  },
  {
    id: 'SAMSUNG_GLOBAL',
    name: 'Samsung',
    category: 'TECH',
    tier: 'ELITE',
    logo: '📱',
    tagline: 'Next is now.',
    budget: 34_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['KR', 'US', 'BR', 'IN', 'GB'],
    maxContracts: 4,
    riskTolerance: 0.34,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante coreana de tecnologia. Compra presença global, mercados grandes e atletas competitivos.',
  },
  {
    id: 'MERCADO_LIVRE',
    name: 'Mercado Livre',
    category: 'CONSUMER',
    tier: 'PREMIUM',
    logo: '📦',
    tagline: 'Chega antes. Vence antes.',
    budget: 13_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['BR', 'AR', 'MX', 'CO', 'CL'],
    maxContracts: 8,
    riskTolerance: 0.62,
    loyaltyFactor: 0.48,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marketplace latino-americano. Procura atletas de alta visibilidade regional e narrativa de crescimento.',
  },
  {
    id: 'AMAZON_GLOBAL',
    name: 'Amazon',
    category: 'CONSUMER',
    tier: 'ELITE',
    logo: '📦',
    tagline: 'Delivered to the world.',
    budget: 36_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['US', 'GB', 'DE', 'JP', 'BR'],
    maxContracts: 3,
    riskTolerance: 0.32,
    loyaltyFactor: 0.52,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marketplace e plataforma global. Quer nomes capazes de vender produtos, documentários e campanhas mundiais.',
  },
  {
    id: 'VIVO_TELECOM',
    name: 'Vivo',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '📡',
    tagline: 'Conectado ao próximo ponto.',
    budget: 7_500_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['BR'],
    maxContracts: 9,
    riskTolerance: 0.38,
    loyaltyFactor: 0.62,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Telecom brasileira. Busca atletas reconhecíveis, confiáveis e presentes no cotidiano do público.',
  },
  {
    id: 'CLARO_TELECOM',
    name: 'Claro',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '📶',
    tagline: 'Sinal forte em todos os courts.',
    budget: 7_200_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['BR', 'MX', 'CO', 'AR'],
    maxContracts: 10,
    riskTolerance: 0.48,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Telecom latino-americana. Valoriza presença regional e atletas com apelo de massa.',
  },

  // AIRLINES / TRAVEL — reais
  {
    id: 'EMIRATES_AIRLINE',
    name: 'Emirates',
    category: 'AIRLINE',
    tier: 'ELITE',
    logo: '✈️',
    tagline: 'Fly better. Win bigger.',
    budget: 32_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['AE', 'GB', 'US', 'FR', 'AU'],
    maxContracts: 3,
    riskTolerance: 0.18,
    loyaltyFactor: 0.86,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Companhia aérea premium. Quer embaixadores globais, elegantes e presentes nos maiores palcos.',
  },
  {
    id: 'QATAR_AIRWAYS',
    name: 'Qatar Airways',
    category: 'AIRLINE',
    tier: 'ELITE',
    logo: '🛫',
    tagline: 'A world-class journey.',
    budget: 29_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['QA', 'GB', 'FR', 'ES', 'US'],
    maxContracts: 3,
    riskTolerance: 0.20,
    loyaltyFactor: 0.82,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca aérea de luxo. Prefere atletas de postura institucional e reputação internacional.',
  },
  {
    id: 'LATAM_AIRLINES',
    name: 'LATAM',
    category: 'AIRLINE',
    tier: 'PREMIUM',
    logo: '🌎',
    tagline: 'A América Latina joga junto.',
    budget: 8_000_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['BR', 'CL', 'AR', 'CO', 'PE'],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.58,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea latino-americana. Investe em jogadores que carregam orgulho regional.',
  },

  // AUTOMOTIVE / LUXURY — reais
  {
    id: 'MERCEDES_BENZ',
    name: 'Mercedes-Benz',
    category: 'AUTOMOTIVE',
    tier: 'ELITE',
    logo: '🚘',
    tagline: 'The best or nothing.',
    budget: 26_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['DE', 'GB', 'US', 'CH'],
    maxContracts: 3,
    riskTolerance: 0.16,
    loyaltyFactor: 0.84,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca automotiva de prestígio. Quer campeões elegantes, maduros e de reputação impecável.',
  },
  {
    id: 'BMW_GLOBAL',
    name: 'BMW',
    category: 'AUTOMOTIVE',
    tier: 'ELITE',
    logo: '🚗',
    tagline: 'Driven by the next point.',
    budget: 22_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['DE', 'US', 'GB', 'CN'],
    maxContracts: 4,
    riskTolerance: 0.30,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Montadora premium. Compra performance, tecnologia e status competitivo.',
  },
  {
    id: 'TOYOTA_GLOBAL',
    name: 'Toyota',
    category: 'AUTOMOTIVE',
    tier: 'PREMIUM',
    logo: '🚙',
    tagline: 'Reliability wins seasons.',
    budget: 13_000_000,
    minMarketability: 60,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['JP', 'US', 'BR', 'AU'],
    maxContracts: 7,
    riskTolerance: 0.28,
    loyaltyFactor: 0.76,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora global de confiança. Gosta de atletas consistentes, duráveis e familiares.',
  },
  {
    id: 'TESLA_MOTORS',
    name: 'Tesla',
    category: 'AUTOMOTIVE',
    tier: 'ELITE',
    logo: '🔋',
    tagline: 'Acceleration is a mindset.',
    budget: 25_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'DE', 'CN', 'NO'],
    maxContracts: 4,
    riskTolerance: 0.62,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca elétrica disruptiva. Prefere atletas futuristas, polarizantes e com imagem de velocidade.',
  },

  // MEDIA / STREAMING / ENTERTAINMENT — reais
  {
    id: 'NETFLIX_GLOBAL',
    name: 'Netflix',
    category: 'MEDIA',
    tier: 'ELITE',
    logo: '🎬',
    tagline: 'Every champion has a series.',
    budget: 24_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'BR', 'GB', 'ES', 'KR'],
    maxContracts: 4,
    riskTolerance: 0.58,
    loyaltyFactor: 0.42,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Streaming global. Procura personagens, rivalidades e atletas que viram documentário.',
  },
  {
    id: 'DISNEY_GLOBAL',
    name: 'Disney',
    category: 'MEDIA',
    tier: 'ELITE',
    logo: '🏰',
    tagline: 'Where heroes become stories.',
    budget: 27_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['US', 'BR', 'JP', 'GB'],
    maxContracts: 3,
    riskTolerance: 0.12,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Império de entretenimento familiar. Exige imagem limpa e narrativa heroica de amplo alcance.',
  },
  {
    id: 'SPOTIFY_GLOBAL',
    name: 'Spotify',
    category: 'MEDIA',
    tier: 'PREMIUM',
    logo: '🎧',
    tagline: 'The sound of match point.',
    budget: 9_000_000,
    minMarketability: 56,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['SE', 'US', 'BR', 'GB', 'MX'],
    maxContracts: 8,
    riskTolerance: 0.58,
    loyaltyFactor: 0.44,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Plataforma de áudio e cultura pop. Busca atletas com personalidade, playlists, podcasts e presença digital.',
  },

  // LUXURY / WATCHES — reais
  {
    id: 'ROLEX_GLOBAL',
    name: 'Rolex',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '⌚',
    tagline: 'Every second becomes legacy.',
    budget: 34_000_000,
    minMarketability: 88,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['CH', 'GB', 'US', 'ES', 'FR'],
    maxContracts: 2,
    riskTolerance: 0.04,
    loyaltyFactor: 0.96,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Símbolo máximo de legado no tênis. Só assina com atletas quase mitológicos e sem ruído público.',
  },
  {
    id: 'LOUIS_VUITTON',
    name: 'Louis Vuitton',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '🧳',
    tagline: 'Travel with greatness.',
    budget: 24_000_000,
    minMarketability: 84,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['FR', 'IT', 'US', 'JP', 'CN'],
    maxContracts: 3,
    riskTolerance: 0.18,
    loyaltyFactor: 0.74,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Casa de moda e viagem de luxo. Procura atletas que transcendem o esporte e viram ícones visuais.',
  },
  {
    id: 'TAG_HEUER',
    name: 'TAG Heuer',
    category: 'LUXURY',
    tier: 'PREMIUM',
    logo: '⏱️',
    tagline: 'Pressure makes precision.',
    budget: 10_000_000,
    minMarketability: 64,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.AGG_BASELINER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['CH', 'DE', 'US', 'AU'],
    maxContracts: 6,
    riskTolerance: 0.36,
    loyaltyFactor: 0.62,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Relojoaria esportiva premium. Quer velocidade, precisão e atletas com aura competitiva.',
  },
  // ── Expansão real: a porta de entrada e o meio do mercado também importam ──
  { id:'ARTENGO', name:'Artengo', category:'RACKET', tier:'ENTRY', logo:'🎾', tagline:'Tennis for everyone.', budget:1_100_000, minMarketability:18, preferredStyles:[], preferredNationality:['FR','ES','BR'], maxContracts:28, riskTolerance:.82, loyaltyFactor:.62, personality:BRAND_PERSONALITIES.UNDERDOG_PATRON, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca acessível que procura histórias de ascensão e presença regional.' },
  { id:'DUNLOP', name:'Dunlop', category:'RACKET', tier:'MID', logo:'🎾', tagline:'Play the long game.', budget:3_800_000, minMarketability:34, preferredStyles:[STYLE_IDS.GRINDER,STYLE_IDS.ALL_COURT], preferredNationality:['GB','JP','AU'], maxContracts:14, riskTolerance:.55, loyaltyFactor:.72, personality:BRAND_PERSONALITIES.HERITAGE, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca histórica que valoriza durabilidade, tradição e atletas consistentes.' },
  { id:'PRINCE', name:'Prince', category:'RACKET', tier:'MID', logo:'🎾', tagline:'Built for the brave.', budget:2_900_000, minMarketability:31, preferredStyles:[STYLE_IDS.SERVE_VOLLEY,STYLE_IDS.SHOWMAN], preferredNationality:['US','JP'], maxContracts:16, riskTolerance:.7, loyaltyFactor:.5, personality:BRAND_PERSONALITIES.INNOVATION, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca de herança técnica que volta a apostar em atletas com assinatura própria.' },
  { id:'TECNIFIBRE', name:'Tecnifibre', category:'RACKET', tier:'PREMIUM', logo:'🎾', tagline:'Play your way.', budget:7_500_000, minMarketability:52, preferredStyles:[STYLE_IDS.AGG_BASELINER,STYLE_IDS.ALL_COURT], preferredNationality:['FR','PL','BR'], maxContracts:9, riskTolerance:.62, loyaltyFactor:.68, personality:BRAND_PERSONALITIES.SURFACE_EXPERT, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca técnica que desenvolve atletas de jogo completo e presença internacional.' },
  { id:'LOTTO', name:'Lotto', category:'APPAREL', tier:'ENTRY', logo:'👟', tagline:'Sport is our language.', budget:1_300_000, minMarketability:17, preferredStyles:[], preferredNationality:['IT','HR','AR'], maxContracts:30, riskTolerance:.76, loyaltyFactor:.58, personality:BRAND_PERSONALITIES.UNDERDOG_PATRON, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Porta de entrada para profissionais que precisam de estrutura e visibilidade.' },
  { id:'JOMA', name:'Joma', category:'APPAREL', tier:'ENTRY', logo:'👟', tagline:'Your sport, your way.', budget:1_450_000, minMarketability:18, preferredStyles:[], preferredNationality:['ES','PT','MX'], maxContracts:28, riskTolerance:.74, loyaltyFactor:.64, personality:BRAND_PERSONALITIES.MASS_APPEAL, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca regional com ambição de acompanhar talentos antes do salto global.' },
  { id:'FILA', name:'Fila', category:'APPAREL', tier:'MID', logo:'👕', tagline:'Heritage in motion.', budget:4_400_000, minMarketability:38, preferredStyles:[STYLE_IDS.ALL_COURT,STYLE_IDS.SHOWMAN], preferredNationality:['IT','KR','BR'], maxContracts:15, riskTolerance:.48, loyaltyFactor:.7, personality:BRAND_PERSONALITIES.HERITAGE, conservativeImage:true, energyBrand:false, luxuryBrand:false, description:'Marca de herança esportiva que busca estilo, história e presença cultural.' },
  { id:'DIADORA', name:'Diadora', category:'APPAREL', tier:'MID', logo:'👟', tagline:'Make it bright.', budget:3_100_000, minMarketability:30, preferredStyles:[STYLE_IDS.COUNTER_PUNCHER,STYLE_IDS.GRINDER], preferredNationality:['IT','ES','SE'], maxContracts:17, riskTolerance:.6, loyaltyFactor:.68, personality:BRAND_PERSONALITIES.SURFACE_EXPERT, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca italiana que valoriza autenticidade, esforço e identidade técnica.' },
  { id:'ON_RUNNING', name:'On', category:'APPAREL', tier:'PREMIUM', logo:'☁️', tagline:'Dream On.', budget:9_000_000, minMarketability:58, preferredStyles:[STYLE_IDS.ALL_COURT,STYLE_IDS.COUNTER_PUNCHER], preferredNationality:['CH','DE','US'], maxContracts:8, riskTolerance:.67, loyaltyFactor:.6, personality:BRAND_PERSONALITIES.INNOVATION, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca de performance contemporânea, obcecada por inovação e crescimento.' },
  { id:'UNIQLO', name:'Uniqlo', category:'APPAREL', tier:'PREMIUM', logo:'👕', tagline:'LifeWear for champions.', budget:10_000_000, minMarketability:60, preferredStyles:[STYLE_IDS.ALL_COURT,STYLE_IDS.SERVE_VOLLEY], preferredNationality:['JP','US','GB','FR'], maxContracts:7, riskTolerance:.34, loyaltyFactor:.84, personality:BRAND_PERSONALITIES.HERITAGE, conservativeImage:true, energyBrand:false, luxuryBrand:false, description:'Marca global de design limpo que procura embaixadores de longo prazo.' },
  { id:'RED_BULL', name:'Red Bull', category:'ENERGY', tier:'PREMIUM', logo:'⚡', tagline:'Gives you wings.', budget:11_000_000, minMarketability:54, preferredStyles:[STYLE_IDS.SHOWMAN,STYLE_IDS.POWER_SERVER], preferredNationality:['AT','US','BR','AU'], maxContracts:10, riskTolerance:.88, loyaltyFactor:.42, personality:BRAND_PERSONALITIES.REBEL_SEEKER, conservativeImage:false, energyBrand:true, luxuryBrand:false, description:'Marca de energia que quer personalidade, risco e momentos inesquecíveis.' },
  { id:'VISA', name:'Visa', category:'FINANCE', tier:'PREMIUM', logo:'💳', tagline:'Everywhere you want to be.', budget:8_500_000, minMarketability:58, preferredStyles:[], preferredNationality:['US','BR','GB','JP'], maxContracts:9, riskTolerance:.3, loyaltyFactor:.78, personality:BRAND_PERSONALITIES.GLOBAL_REACH, conservativeImage:true, energyBrand:false, luxuryBrand:false, description:'Marca financeira global focada em confiança, alcance e grandes palcos.' },
  { id:'JBL', name:'JBL', category:'TECH', tier:'MID', logo:'🔊', tagline:'Dare to listen.', budget:3_500_000, minMarketability:34, preferredStyles:[STYLE_IDS.SHOWMAN], preferredNationality:['US','BR','IN'], maxContracts:18, riskTolerance:.72, loyaltyFactor:.5, personality:BRAND_PERSONALITIES.MASS_APPEAL, conservativeImage:false, energyBrand:false, luxuryBrand:false, description:'Marca de áudio que procura atletas conectados à cultura e ao público jovem.' },
];

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS DE ACESSO
// ─────────────────────────────────────────────────────────────────────────────

/** Retorna o perfil de um patrocinador pelo id */
export function getSponsorById(id) {
  return SPONSOR_CATALOG.find(s => s.id === id) ?? null;
}

/** Retorna todas as marcas de uma categoria */
export function getSponsorsByCategory(category) {
  return SPONSOR_CATALOG.filter(s => s.category === category);
}

/** Retorna todas as marcas de um tier */
export function getSponsorsByTier(tier) {
  return SPONSOR_CATALOG.filter(s => s.tier === tier);
}

/** Retorna o objeto SPONSOR_TIERS para um id de tier */
export function getTierData(tierId) {
  return SPONSOR_TIERS[tierId] ?? SPONSOR_TIERS.ENTRY;
}

/** Retorna a faixa de contrato esperada para um tier (em USD/ano) */
export function getContractRange(tierId) {
  return getTierData(tierId).contractRange;
}

