/**
 * SponsorProfiles.js — Fase 3: Catálogo de Patrocinadores
 *
 * Elenco permanente do universo: ~70 marcas com personalidade,
 * orçamento, critérios de investimento e comportamento próprio.
 *
 * Cada marca tem:
 *   id, name, category, tier, logo (emoji), tagline
 *   budget               — total disponível por temporada para contratos
 *   minMarketability     — score mínimo para considerar o jogador
 *   preferredStyles[]    — estilos de jogo preferidos
 *   preferredNationality[] — mercados prioritários (ISO-2)
 *   maxContracts         — máximo de contratos ativos simultâneos
 *   riskTolerance        — 0–1: prefere jovens prospects vs veteranos
 *   loyaltyFactor        — 0–1: tende a renovar vs trocar
 *   personality          — arquétipo de marca (afeta narrativa)
 *   conservativeImage    — boolean: rescinde por escândalo?
 *   energyBrand          — boolean: prefere IFR alto sobre tudo
 *   luxuryBrand          — boolean: prefere veteranos campeões
 *   preferredSurface     — superfície favorita (opcional)
 *   description          — texto narrativo (para ChronicleEngine)
 *
 * CATEGORIAS:
 *   RACKET     — raquetes e equipamento de jogo
 *   APPAREL    — roupas e calçados esportivos
 *   LUXURY     — relógios, carros, moda de luxo
 *   FINANCE    — bancos, seguros, fintechs
 *   TECH       — tecnologia, apps, eletrônicos
 *   ENERGY     — bebidas energéticas e nutrição
 *   AUTOMOTIVE — automóveis (não luxo)
 *   AIRLINE    — companhias aéreas
 *   RETAIL     — varejo esportivo e consumo geral
 *   MEDIA      — streaming, mídia e entretenimento
 */

// ─────────────────────────────────────────────────────────────────────────────
// ESTILOS DE JOGO (mirror de styles.js — ids usados em preferredStyles)
// ─────────────────────────────────────────────────────────────────────────────
export const STYLE_IDS = {
  AGG_BASELINER:   'AGG_BASELINER',
  DEF_BASELINER:   'DEF_BASELINER',
  SERVE_VOLLEY:    'SERVE_VOLLEY',
  COUNTER_PUNCHER: 'COUNTER_PUNCHER',
  ALL_COURT:       'ALL_COURT',
  POWER_SERVER:    'POWER_SERVER',
  SHOWMAN:         'SHOWMAN',
  GRINDER:         'GRINDER',
};

// ─────────────────────────────────────────────────────────────────────────────
// TIERS — faixas de contrato e requisitos
// ─────────────────────────────────────────────────────────────────────────────
export const SPONSOR_TIERS = {
  ENTRY: {
    id:            'ENTRY',
    label:         'Entry',
    color:         '#8899AA',
    glow:          'rgba(136,153,170,0.20)',
    contractRange: [50_000, 200_000],
    minMarket:     20,
    maxContracts:  999,
    description:   'Marcas regionais e equipamentos locais.',
  },
  MID: {
    id:            'MID',
    label:         'Mid',
    color:         '#60C8FF',
    glow:          'rgba(96,200,255,0.25)',
    contractRange: [200_000, 800_000],
    minMarket:     40,
    maxContracts:  20,
    description:   'Marcas nacionais e equipamentos mid-tier.',
  },
  PREMIUM: {
    id:            'PREMIUM',
    label:         'Premium',
    color:         '#60FF90',
    glow:          'rgba(96,255,144,0.30)',
    contractRange: [800_000, 3_000_000],
    minMarket:     60,
    maxContracts:  8,
    description:   'Nike, Adidas, Babolat — o topo do mainstream.',
  },
  ELITE: {
    id:            'ELITE',
    label:         'Elite',
    color:         '#FFD700',
    glow:          'rgba(255,215,0,0.40)',
    contractRange: [3_000_000, 15_000_000],
    minMarket:     80,
    maxContracts:  3,
    description:   'Rolex, Emirates, Apple — contratos que definem legado.',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// PERSONALIDADES DE MARCA
// ─────────────────────────────────────────────────────────────────────────────
export const BRAND_PERSONALITIES = {
  CHAMPION_HUNTER:   'CHAMPION_HUNTER',   // quer o nº1 / campeão do GS
  REBEL_SEEKER:      'REBEL_SEEKER',      // quer o ousado, o controverso
  HERITAGE:          'HERITAGE',          // quer o elegante, o clássico
  INNOVATION:        'INNOVATION',        // quer o jovem talento, o futuro
  MASS_APPEAL:       'MASS_APPEAL',       // quer o mais popular, mais fãs
  UNDERDOG_PATRON:   'UNDERDOG_PATRON',   // apostador em prospects
  SURFACE_EXPERT:    'SURFACE_EXPERT',    // quer especialistas de superfície
  GLOBAL_REACH:      'GLOBAL_REACH',      // prefere jogadores de mercados grandes
};

// ─────────────────────────────────────────────────────────────────────────────
// CATÁLOGO DE PATROCINADORES
// ─────────────────────────────────────────────────────────────────────────────

export const SPONSOR_CATALOG = [

  // ═══════════════════════════════════════════════════════════════
  // RAQUETES — ELITE / PREMIUM
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'APEX_RACKETS',
    name: 'Apex',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '🎾',
    tagline: 'O jogo começa aqui.',
    budget: 18_000_000,
    minMarketability: 75,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER, STYLE_IDS.SHOWMAN],
    preferredNationality: [],
    maxContracts: 4,
    riskTolerance: 0.3,
    loyaltyFactor: 0.75,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'A maior fabricante de raquetes do mundo. Só quer campeões.',
  },
  {
    id: 'STRATO_SPORTS',
    name: 'Strato',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🎾',
    tagline: 'Precisão. Velocidade. Domínio.',
    budget: 8_000_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.GRINDER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.5,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Aposta em jogadores consistentes e de alta durabilidade de carreira.',
  },
  {
    id: 'VOLT_FRAME',
    name: 'Volt',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '⚡',
    tagline: 'Mais potência. Menos limites.',
    budget: 6_500_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'AU', 'DE'],
    maxContracts: 8,
    riskTolerance: 0.6,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca americana que aposta em jovens agressivos.',
  },
  {
    id: 'TIERRA_RACKETS',
    name: 'Tierra',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🧱',
    tagline: 'Feito para saibro. Feito para durar.',
    budget: 5_000_000,
    minMarketability: 45,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['ES', 'AR', 'FR', 'IT'],
    maxContracts: 10,
    riskTolerance: 0.5,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.SURFACE_EXPERT,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    preferredSurface: 'CLAY',
    description: 'Marca espanhola especialista em saibro. Lealdade extrema aos seus atletas.',
  },
  {
    id: 'GREENLINE_RACKETS',
    name: 'Greenline',
    category: 'RACKET',
    tier: 'MID',
    logo: '🌿',
    tagline: 'Sustentável. Competitivo.',
    budget: 2_500_000,
    minMarketability: 35,
    preferredStyles: [],
    preferredNationality: ['GB', 'AU', 'NZ', 'SE'],
    maxContracts: 15,
    riskTolerance: 0.55,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca britânica com foco em sustentabilidade e mercados anglófonos.',
  },
  {
    id: 'NOVA_RACKETS',
    name: 'Nova',
    category: 'RACKET',
    tier: 'MID',
    logo: '🌟',
    tagline: 'O próximo nível.',
    budget: 1_800_000,
    minMarketability: 30,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 20,
    riskTolerance: 0.75,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Especialista em revelar talentos. Aposta alto em prospects.',
  },

  // ═══════════════════════════════════════════════════════════════
  // APPAREL — ELITE / PREMIUM
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'NEON_SPORTS',
    name: 'Neon',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '👟',
    tagline: 'Vista a vitória.',
    budget: 22_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'BR', 'FR', 'JP'],
    maxContracts: 3,
    riskTolerance: 0.2,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'O maior contrato de vestuário do circuito. Exige campeões e carisma.',
  },
  {
    id: 'CREST_APPAREL',
    name: 'Crest',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '👔',
    tagline: 'Elegância em movimento.',
    budget: 16_000_000,
    minMarketability: 75,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.SHOWMAN],
    preferredNationality: ['GB', 'SE', 'CH', 'AT'],
    maxContracts: 3,
    riskTolerance: 0.15,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca britânica clássica. Quer elegância e títulos em Wimbledon.',
  },
  {
    id: 'STRIKER_WEAR',
    name: 'Striker',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '⚔️',
    tagline: 'Feito para atacar.',
    budget: 9_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'AU', 'CA'],
    maxContracts: 8,
    riskTolerance: 0.55,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Americana agressiva. Gosta de jogadores que dominam pelo poder.',
  },
  {
    id: 'ARENA_SPORT',
    name: 'Arena',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '🏟️',
    tagline: 'Cada quadra. Cada clima.',
    budget: 7_500_000,
    minMarketability: 52,
    preferredStyles: [],
    preferredNationality: ['IT', 'FR', 'ES', 'PT'],
    maxContracts: 8,
    riskTolerance: 0.45,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Italiana com forte presença no circuito europeu de saibro.',
  },
  {
    id: 'RUSH_ATHLETIC',
    name: 'Rush',
    category: 'APPAREL',
    tier: 'MID',
    logo: '💨',
    tagline: 'Mais rápido. Mais forte.',
    budget: 2_200_000,
    minMarketability: 38,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.GRINDER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.65,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Aposta em defensores e jogadores de alta resistência.',
  },

  // ═══════════════════════════════════════════════════════════════
  // LUXURY
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'MERIDIAN_WATCHES',
    name: 'Meridian',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '⌚',
    tagline: 'O tempo pertence aos campeões.',
    budget: 20_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['CH', 'DE', 'AT', 'GB'],
    maxContracts: 3,
    riskTolerance: 0.05,
    loyaltyFactor: 0.95,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Relojoaria suíça. Quer apenas campeões estabelecidos. Lealdade absoluta.',
  },
  {
    id: 'AURUM_MOTORS',
    name: 'Aurum',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '🚗',
    tagline: 'A excelência move o mundo.',
    budget: 15_000_000,
    minMarketability: 78,
    preferredStyles: [],
    preferredNationality: ['DE', 'GB', 'US', 'JP', 'KR'],
    maxContracts: 3,
    riskTolerance: 0.10,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Montadora de luxo alemã. Exige imagem impecável e alcance global.',
  },
  {
    id: 'CIEL_FASHION',
    name: 'Ciel',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '👑',
    tagline: 'Além do esporte.',
    budget: 12_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['FR', 'IT', 'ES'],
    maxContracts: 3,
    riskTolerance: 0.08,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Alta moda francesa. Quer o jogador-ícone que transcende o esporte.',
  },
  {
    id: 'ONYX_PRESTIGE',
    name: 'Onyx',
    category: 'LUXURY',
    tier: 'PREMIUM',
    logo: '💎',
    tagline: 'Para quem exige o melhor.',
    budget: 4_500_000,
    minMarketability: 65,
    preferredStyles: [],
    preferredNationality: ['AE', 'CN', 'RU', 'SA'],
    maxContracts: 6,
    riskTolerance: 0.20,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca premium dos Emirados. Foco em mercados de alto crescimento.',
  },

  // ═══════════════════════════════════════════════════════════════
  // TECHNOLOGY
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'NEXUS_TECH',
    name: 'Nexus',
    category: 'TECH',
    tier: 'ELITE',
    logo: '📱',
    tagline: 'Conecte-se ao futuro.',
    budget: 25_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'JP', 'KR', 'CN', 'IN'],
    maxContracts: 3,
    riskTolerance: 0.35,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante de tecnologia. Quer o rosto do esporte conectado.',
  },
  {
    id: 'PULSE_WEARABLES',
    name: 'Pulse',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '⌚',
    tagline: 'Monitore cada batalha.',
    budget: 5_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.60,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Wearables esportivos. Prefere jogadores com narrativa de performance.',
  },
  {
    id: 'CODEC_STREAMING',
    name: 'Codec',
    category: 'MEDIA',
    tier: 'PREMIUM',
    logo: '📺',
    tagline: 'Todo ponto. Ao vivo.',
    budget: 6_000_000,
    minMarketability: 60,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['US', 'BR', 'MX'],
    maxContracts: 6,
    riskTolerance: 0.45,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Plataforma de streaming de esportes. Quer faces reconhecíveis.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENERGY / NUTRITION
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'VOLT_ENERGY',
    name: 'Volt Energy',
    category: 'ENERGY',
    tier: 'PREMIUM',
    logo: '⚡',
    tagline: 'Energia sem limites.',
    budget: 7_000_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'AU', 'DE', 'BR'],
    maxContracts: 7,
    riskTolerance: 0.80,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Bebida energética. Prefere jovens com IFR alto e atitude. Baixa lealdade.',
  },
  {
    id: 'APEX_NUTRITION',
    name: 'Apex Nutrition',
    category: 'ENERGY',
    tier: 'PREMIUM',
    logo: '💪',
    tagline: 'Performance de elite.',
    budget: 5_000_000,
    minMarketability: 48,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.65,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Suplementos. Gosta de jogadores que simbolizam disciplina e resistência.',
  },
  {
    id: 'STORM_DRINKS',
    name: 'Storm',
    category: 'ENERGY',
    tier: 'MID',
    logo: '🌩️',
    tagline: 'Libera a tempestade.',
    budget: 1_800_000,
    minMarketability: 32,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: [],
    maxContracts: 15,
    riskTolerance: 0.85,
    loyaltyFactor: 0.25,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Marca jovem. Aposta agressiva em prospects com potencial explosivo.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AIRLINES
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ALTITUDE_AIRLINES',
    name: 'Altitude Airlines',
    category: 'AIRLINE',
    tier: 'ELITE',
    logo: '✈️',
    tagline: 'O mundo é a sua quadra.',
    budget: 18_000_000,
    minMarketability: 76,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 3,
    riskTolerance: 0.10,
    loyaltyFactor: 0.75,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea premium. Quer um embaixador global reconhecível.',
  },
  {
    id: 'SKYPATH_AIRLINES',
    name: 'SkyPath',
    category: 'AIRLINE',
    tier: 'PREMIUM',
    logo: '🛫',
    tagline: 'Conectando campeões.',
    budget: 4_000_000,
    minMarketability: 58,
    preferredStyles: [],
    preferredNationality: ['BR', 'AR', 'CL', 'CO', 'MX'],
    maxContracts: 6,
    riskTolerance: 0.40,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia sul-americana. Prioriza jogadores do continente.',
  },

  // ═══════════════════════════════════════════════════════════════
  // FINANCE
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'CAPITAL_BANK',
    name: 'Capital',
    category: 'FINANCE',
    tier: 'ELITE',
    logo: '🏦',
    tagline: 'Invista no que importa.',
    budget: 14_000_000,
    minMarketability: 78,
    preferredStyles: [],
    preferredNationality: ['US', 'GB', 'JP', 'AU'],
    maxContracts: 3,
    riskTolerance: 0.08,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco global. Imagem conservadora absoluta. Lealdade extrema.',
  },
  {
    id: 'ZENITH_FINTECH',
    name: 'Zenith',
    category: 'FINANCE',
    tier: 'PREMIUM',
    logo: '💳',
    tagline: 'O dinheiro do futuro.',
    budget: 6_000_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: ['US', 'IN', 'CN', 'BR'],
    maxContracts: 6,
    riskTolerance: 0.50,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fintech disruptiva. Quer o jogador que representa a nova geração.',
  },
  {
    id: 'FORTIS_INSURANCE',
    name: 'Fortis',
    category: 'FINANCE',
    tier: 'MID',
    logo: '🛡️',
    tagline: 'Proteja o que importa.',
    budget: 1_500_000,
    minMarketability: 38,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.GRINDER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.20,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Seguradora europeia. Prefere defensores — a metáfora é óbvia.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AUTOMOTIVE (não luxo)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'TORQUE_MOTORS',
    name: 'Torque',
    category: 'AUTOMOTIVE',
    tier: 'PREMIUM',
    logo: '🏎️',
    tagline: 'Da linha de saída à vitória.',
    budget: 8_000_000,
    minMarketability: 60,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['US', 'DE', 'AU'],
    maxContracts: 6,
    riskTolerance: 0.40,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora americana de performance. Gosta de jogadores agressivos.',
  },
  {
    id: 'VERDE_EV',
    name: 'Verde',
    category: 'AUTOMOTIVE',
    tier: 'MID',
    logo: '🔋',
    tagline: 'O futuro, sem emissões.',
    budget: 2_000_000,
    minMarketability: 42,
    preferredStyles: [],
    preferredNationality: ['DE', 'NL', 'SE', 'NO'],
    maxContracts: 14,
    riskTolerance: 0.55,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora europeia de elétricos. Prefere atletas com imagem sustentável.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RETAIL
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'SPORT_ZONE',
    name: 'Sport Zone',
    category: 'RETAIL',
    tier: 'MID',
    logo: '🏪',
    tagline: 'Tudo para o seu esporte.',
    budget: 2_800_000,
    minMarketability: 35,
    preferredStyles: [],
    preferredNationality: ['BR', 'PT', 'ES', 'MX'],
    maxContracts: 20,
    riskTolerance: 0.45,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Varejista esportiva lusófona. Ampla base de contratos, valores modestos.',
  },
  {
    id: 'COURT_KING_RETAIL',
    name: 'Court King',
    category: 'RETAIL',
    tier: 'ENTRY',
    logo: '👑',
    tagline: 'O rei começa aqui.',
    budget: 800_000,
    minMarketability: 20,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.90,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Varejista online de materiais de tênis. Porta de entrada para prospects.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENTRY — complementos regionais
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ALPHA_STRING_CO',
    name: 'Alpha Strings',
    category: 'RACKET',
    tier: 'ENTRY',
    logo: '🎵',
    tagline: 'A tensão certa para cada jogo.',
    budget: 500_000,
    minMarketability: 18,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.85,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fabricante de cordas. Primeira marca a apostar em prospects desconhecidos.',
  },
  {
    id: 'HYDRO_SPORTS_DRINK',
    name: 'Hydro',
    category: 'ENERGY',
    tier: 'ENTRY',
    logo: '💧',
    tagline: 'Hidrate-se. Vença.',
    budget: 600_000,
    minMarketability: 22,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.70,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Bebida isotônica entry-level. Principal parceiro de jovens no circuito.',
  },
  {
    id: 'BASELINE_APPAREL',
    name: 'Baseline',
    category: 'APPAREL',
    tier: 'ENTRY',
    logo: '👕',
    tagline: 'Começando pelo começo.',
    budget: 700_000,
    minMarketability: 18,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.80,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Roupa esportiva entry. Veste qualquer jogador disposto a usar o logo.',
  },
  {
    id: 'REGIONAL_BANK_EU',
    name: 'EuroBanca',
    category: 'FINANCE',
    tier: 'ENTRY',
    logo: '🏛️',
    tagline: 'Próxima de você.',
    budget: 400_000,
    minMarketability: 20,
    preferredStyles: [],
    preferredNationality: ['IT', 'FR', 'ES', 'PT', 'GR'],
    maxContracts: 999,
    riskTolerance: 0.30,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco regional europeu. Apoia atletas locais com contratos pequenos e duradouros.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RACKET — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'KRONOS_RACKETS',
    name: 'Kronos',
    category: 'RACKET',
    tier: 'ELITE',
    logo: '⚙️',
    tagline: 'Engenharia sem concessões.',
    budget: 14_000_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['DE', 'AT', 'CH', 'CZ'],
    maxContracts: 3,
    riskTolerance: 0.25,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca alemã de engenharia de precisão. Prefere jogadores completos e duradouros.',
  },
  {
    id: 'FALCON_RACKETS',
    name: 'Falcon',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🦅',
    tagline: 'Velocidade no primeiro serviço.',
    budget: 7_500_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['US', 'AU', 'CA'],
    maxContracts: 7,
    riskTolerance: 0.55,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca americana especializada em jogadores de serviço dominante.',
  },
  {
    id: 'KAZE_RACKETS',
    name: 'Kaze',
    category: 'RACKET',
    tier: 'PREMIUM',
    logo: '🌊',
    tagline: 'Leveza que corta o vento.',
    budget: 5_500_000,
    minMarketability: 45,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['JP', 'KR', 'CN', 'TW'],
    maxContracts: 10,
    riskTolerance: 0.45,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.SURFACE_EXPERT,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca japonesa de alta precisão. Leal aos seus atletas asiáticos.',
  },
  {
    id: 'REDLINE_RACKETS',
    name: 'Redline',
    category: 'RACKET',
    tier: 'MID',
    logo: '🔴',
    tagline: 'No limite. Sempre.',
    budget: 2_000_000,
    minMarketability: 32,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.70,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca jovem que busca personagens agressivos e controversos.',
  },
  {
    id: 'SWIFT_RACKETS',
    name: 'Swift',
    category: 'RACKET',
    tier: 'MID',
    logo: '💨',
    tagline: 'Reação em milissegundos.',
    budget: 1_600_000,
    minMarketability: 28,
    preferredStyles: [STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: ['GB', 'IE', 'AU'],
    maxContracts: 20,
    riskTolerance: 0.60,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Aposta em jogadores de net e contra-atacantes em desenvolvimento.',
  },
  {
    id: 'OPEN_COURT_RACKETS',
    name: 'Open Court',
    category: 'RACKET',
    tier: 'ENTRY',
    logo: '🎾',
    tagline: 'Para quem começa a jogar sério.',
    budget: 500_000,
    minMarketability: 18,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.80,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fabricante de entrada que aposta em prospects sem nome.',
  },

  // ═══════════════════════════════════════════════════════════════
  // APPAREL — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'VICTOIRE_APPAREL',
    name: 'Victoire',
    category: 'APPAREL',
    tier: 'ELITE',
    logo: '🏅',
    tagline: 'A elegância como vantagem.',
    budget: 20_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY, STYLE_IDS.SHOWMAN],
    preferredNationality: ['FR', 'IT', 'ES', 'BE'],
    maxContracts: 3,
    riskTolerance: 0.20,
    loyaltyFactor: 0.90,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca francesa de vestuário esportivo de luxo. Quer campeões com elegância.',
  },
  {
    id: 'KINETIC_APPAREL',
    name: 'Kinetic',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '⚡',
    tagline: 'Movimento sem atrito.',
    budget: 8_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Foco em tecnologia de tecido e performance extrema. Adora jovens talentos.',
  },
  {
    id: 'VALOR_APPAREL',
    name: 'Valor',
    category: 'APPAREL',
    tier: 'PREMIUM',
    logo: '🛡️',
    tagline: 'Veste quem não desiste.',
    budget: 6_500_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.GRINDER, STYLE_IDS.DEF_BASELINER],
    preferredNationality: ['BR', 'AR', 'CO', 'CL'],
    maxContracts: 9,
    riskTolerance: 0.55,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca latino-americana que celebra resiliência e guerreiros da quadra.',
  },
  {
    id: 'SPRINT_WEAR',
    name: 'Sprint',
    category: 'APPAREL',
    tier: 'MID',
    logo: '🏃',
    tagline: 'Cada ponto, um sprint.',
    budget: 2_000_000,
    minMarketability: 30,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.65,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Marca de volume que quer atletas populares e acessíveis ao público.',
  },
  {
    id: 'COAST_ATHLETIC',
    name: 'Coast',
    category: 'APPAREL',
    tier: 'MID',
    logo: '🌊',
    tagline: 'Do court para a praia.',
    budget: 1_700_000,
    minMarketability: 28,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['AU', 'US', 'BR', 'ZA'],
    maxContracts: 20,
    riskTolerance: 0.70,
    loyaltyFactor: 0.40,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Estilo descontraído de países costeiros. Prefere personalidades fortes.',
  },
  {
    id: 'MATCH_POINT_APPAREL',
    name: 'Match Point',
    category: 'APPAREL',
    tier: 'ENTRY',
    logo: '🎽',
    tagline: 'Pronto para jogar.',
    budget: 350_000,
    minMarketability: 15,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.85,
    loyaltyFactor: 0.25,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Vestuário de entrada. Financia qualquer atleta promissor.',
  },

  // ═══════════════════════════════════════════════════════════════
  // LUXURY — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'LUMIERE_JEWELS',
    name: 'Lumière',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '💎',
    tagline: 'Brilho que transcende o jogo.',
    budget: 17_000_000,
    minMarketability: 82,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT],
    preferredNationality: ['FR', 'IT', 'CH', 'GB'],
    maxContracts: 2,
    riskTolerance: 0.15,
    loyaltyFactor: 0.95,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Joalheria francesa de alta costura. Quer apenas ícones sem escândalos.',
  },
  {
    id: 'OBSIDIAN_SPIRITS',
    name: 'Obsidian',
    category: 'LUXURY',
    tier: 'ELITE',
    logo: '🥃',
    tagline: 'Para os que sabem o que querem.',
    budget: 13_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SERVE_VOLLEY],
    preferredNationality: ['GB', 'IE', 'US', 'JP'],
    maxContracts: 3,
    riskTolerance: 0.30,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Marca de whisky de luxo. Quer o campeão mais elegante do circuito.',
  },
  {
    id: 'ARGENT_LUXURY',
    name: 'Argent',
    category: 'LUXURY',
    tier: 'PREMIUM',
    logo: '🥈',
    tagline: 'Quase o topo. E com estilo.',
    budget: 4_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.SHOWMAN],
    preferredNationality: [],
    maxContracts: 6,
    riskTolerance: 0.40,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Joia premium acessível. Quer jogadores populares com boa imagem.',
  },

  // ═══════════════════════════════════════════════════════════════
  // TECH — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'SYNAPSE_TECH',
    name: 'Synapse',
    category: 'TECH',
    tier: 'ELITE',
    logo: '🧠',
    tagline: 'A inteligência do jogo.',
    budget: 28_000_000,
    minMarketability: 80,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 4,
    riskTolerance: 0.35,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gigante global de IA e tecnologia. O maior budget do circuito.',
  },
  {
    id: 'ORBIT_STREAMING',
    name: 'Orbit',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '📡',
    tagline: 'Transmitindo cada momento.',
    budget: 7_000_000,
    minMarketability: 58,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.55,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Plataforma de streaming esportivo. Quer atletas que geram audiência.',
  },
  {
    id: 'WAVE_WEARABLES',
    name: 'Wave',
    category: 'TECH',
    tier: 'PREMIUM',
    logo: '⌚',
    tagline: 'Mede tudo. Supera tudo.',
    budget: 5_000_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.COUNTER_PUNCHER],
    preferredNationality: [],
    maxContracts: 10,
    riskTolerance: 0.60,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Wearables de performance. Adora prospects com alto potencial técnico.',
  },
  {
    id: 'MESH_GAMING',
    name: 'Mesh',
    category: 'TECH',
    tier: 'MID',
    logo: '🎮',
    tagline: 'Joga no digital. Domina no court.',
    budget: 1_800_000,
    minMarketability: 30,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER],
    preferredNationality: ['KR', 'CN', 'JP', 'US'],
    maxContracts: 15,
    riskTolerance: 0.75,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Gaming crossover. Quer atletas jovens e com presença em redes sociais.',
  },

  // ═══════════════════════════════════════════════════════════════
  // MEDIA — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'NETPLAY_MEDIA',
    name: 'NetPlay',
    category: 'MEDIA',
    tier: 'PREMIUM',
    logo: '📺',
    tagline: 'O tênis que o mundo quer ver.',
    budget: 5_500_000,
    minMarketability: 55,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.ALL_COURT, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Canal esportivo global. Prefere atletas que geram debate e audiência.',
  },
  {
    id: 'RALLY_TV',
    name: 'Rally TV',
    category: 'MEDIA',
    tier: 'MID',
    logo: '📻',
    tagline: 'Ponto por ponto.',
    budget: 1_500_000,
    minMarketability: 28,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 20,
    riskTolerance: 0.65,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Emissora regional esportiva. Adora revelar novos talentos para o público.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ENERGY — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'PRIME_ENERGY',
    name: 'Prime',
    category: 'ENERGY',
    tier: 'ELITE',
    logo: '🔋',
    tagline: 'Energia no nível máximo.',
    budget: 19_000_000,
    minMarketability: 75,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.SHOWMAN, STYLE_IDS.POWER_SERVER],
    preferredNationality: [],
    maxContracts: 4,
    riskTolerance: 0.45,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Maior marca de energia do circuito. Quer os mais intensos e vencedores.',
  },
  {
    id: 'SURGE_ENERGY',
    name: 'Surge',
    category: 'ENERGY',
    tier: 'MID',
    logo: '⚡',
    tagline: 'Mais explosão, menos desculpa.',
    budget: 1_600_000,
    minMarketability: 28,
    preferredStyles: [STYLE_IDS.POWER_SERVER, STYLE_IDS.AGG_BASELINER],
    preferredNationality: [],
    maxContracts: 18,
    riskTolerance: 0.72,
    loyaltyFactor: 0.38,
    personality: BRAND_PERSONALITIES.REBEL_SEEKER,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Bebida energética rebelde. Busca atletas com atitude.',
  },
  {
    id: 'CARBO_NUTRITION',
    name: 'Carbo',
    category: 'ENERGY',
    tier: 'ENTRY',
    logo: '🥤',
    tagline: 'Combustível para cada treino.',
    budget: 350_000,
    minMarketability: 15,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.85,
    loyaltyFactor: 0.30,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: true,
    luxuryBrand: false,
    description: 'Suplemento de entrada. Assina qualquer atleta disposto a divulgar.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AIRLINE — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'HORIZON_AIRLINES',
    name: 'Horizon Global',
    category: 'AIRLINE',
    tier: 'ELITE',
    logo: '✈️',
    tagline: 'Conectando campeões ao mundo.',
    budget: 22_000_000,
    minMarketability: 78,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 3,
    riskTolerance: 0.20,
    loyaltyFactor: 0.85,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea global premium. Quer embaixadores com alcance mundial.',
  },
  {
    id: 'PACIFIC_WINGS',
    name: 'Pacific Wings',
    category: 'AIRLINE',
    tier: 'PREMIUM',
    logo: '🛫',
    tagline: 'Voe com os melhores.',
    budget: 4_500_000,
    minMarketability: 50,
    preferredStyles: [],
    preferredNationality: ['AU', 'JP', 'CN', 'KR', 'NZ'],
    maxContracts: 7,
    riskTolerance: 0.40,
    loyaltyFactor: 0.65,
    personality: BRAND_PERSONALITIES.GLOBAL_REACH,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Companhia aérea do Pacífico. Foco em atletas da região Ásia-Pacífico.',
  },

  // ═══════════════════════════════════════════════════════════════
  // FINANCE — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'ATLAS_CAPITAL',
    name: 'Atlas Capital',
    category: 'FINANCE',
    tier: 'ELITE',
    logo: '🌐',
    tagline: 'O peso do mundo. A força dos seus investimentos.',
    budget: 16_000_000,
    minMarketability: 76,
    preferredStyles: [STYLE_IDS.ALL_COURT, STYLE_IDS.DEF_BASELINER],
    preferredNationality: [],
    maxContracts: 3,
    riskTolerance: 0.25,
    loyaltyFactor: 0.80,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fundo de investimento global. Quer associar sua marca a campeões estáveis.',
  },
  {
    id: 'STERLING_BANK',
    name: 'Sterling',
    category: 'FINANCE',
    tier: 'PREMIUM',
    logo: '💷',
    tagline: 'Patrimônio construído com consistência.',
    budget: 5_000_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.DEF_BASELINER, STYLE_IDS.GRINDER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['GB', 'IE', 'AU', 'NZ', 'CA'],
    maxContracts: 8,
    riskTolerance: 0.30,
    loyaltyFactor: 0.75,
    personality: BRAND_PERSONALITIES.HERITAGE,
    conservativeImage: true,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Banco britânico tradicional. Valoriza atletas consistentes e de longa carreira.',
  },
  {
    id: 'COMET_CREDIT',
    name: 'Comet',
    category: 'FINANCE',
    tier: 'MID',
    logo: '☄️',
    tagline: 'Rápido como você.',
    budget: 1_400_000,
    minMarketability: 25,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 25,
    riskTolerance: 0.65,
    loyaltyFactor: 0.45,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Fintech de cartões digitais. Quer associação com velocidade e modernidade.',
  },

  // ═══════════════════════════════════════════════════════════════
  // AUTOMOTIVE — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'VELOCE_MOTORS',
    name: 'Veloce',
    category: 'AUTOMOTIVE',
    tier: 'ELITE',
    logo: '🏎️',
    tagline: 'A performance que define o sucesso.',
    budget: 16_500_000,
    minMarketability: 78,
    preferredStyles: [STYLE_IDS.SHOWMAN, STYLE_IDS.AGG_BASELINER, STYLE_IDS.POWER_SERVER],
    preferredNationality: ['IT', 'DE', 'GB', 'FR'],
    maxContracts: 3,
    riskTolerance: 0.35,
    loyaltyFactor: 0.70,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: true,
    description: 'Montadora italiana de supercars. Quer os maiores nomes do circuito.',
  },
  {
    id: 'DRIFT_MOTORS',
    name: 'Drift',
    category: 'AUTOMOTIVE',
    tier: 'PREMIUM',
    logo: '🚗',
    tagline: 'Controle na curva. Domínio na reta.',
    budget: 5_500_000,
    minMarketability: 50,
    preferredStyles: [STYLE_IDS.COUNTER_PUNCHER, STYLE_IDS.ALL_COURT],
    preferredNationality: ['DE', 'JP', 'KR'],
    maxContracts: 7,
    riskTolerance: 0.45,
    loyaltyFactor: 0.60,
    personality: BRAND_PERSONALITIES.INNOVATION,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora asiático-europeia que quer atletas técnicos e precisos.',
  },
  {
    id: 'URBAN_DRIVE',
    name: 'Urban Drive',
    category: 'AUTOMOTIVE',
    tier: 'MID',
    logo: '🚙',
    tagline: 'Da cidade à vitória.',
    budget: 1_500_000,
    minMarketability: 25,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 20,
    riskTolerance: 0.60,
    loyaltyFactor: 0.50,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Montadora urbana acessível. Quer popularidade e volume de público.',
  },

  // ═══════════════════════════════════════════════════════════════
  // RETAIL — novos patrocinadores
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'CHAMPIONS_DEN',
    name: "Champion's Den",
    category: 'RETAIL',
    tier: 'PREMIUM',
    logo: '🏆',
    tagline: 'O esporte dos campeões. Ao seu alcance.',
    budget: 4_500_000,
    minMarketability: 52,
    preferredStyles: [STYLE_IDS.AGG_BASELINER, STYLE_IDS.SHOWMAN],
    preferredNationality: [],
    maxContracts: 8,
    riskTolerance: 0.50,
    loyaltyFactor: 0.55,
    personality: BRAND_PERSONALITIES.CHAMPION_HUNTER,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Cadeia premium de artigos esportivos. Quer campeões como rosto da marca.',
  },
  {
    id: 'GAME_ON_RETAIL',
    name: 'Game On',
    category: 'RETAIL',
    tier: 'MID',
    logo: '🛒',
    tagline: 'Equipado para vencer.',
    budget: 1_300_000,
    minMarketability: 22,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 25,
    riskTolerance: 0.70,
    loyaltyFactor: 0.35,
    personality: BRAND_PERSONALITIES.MASS_APPEAL,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Rede de lojas de artigos esportivos com foco em volume e visibilidade.',
  },
  {
    id: 'PARK_TENNIS',
    name: 'Park Tennis',
    category: 'RETAIL',
    tier: 'ENTRY',
    logo: '🌳',
    tagline: 'Comece onde quiser.',
    budget: 280_000,
    minMarketability: 12,
    preferredStyles: [],
    preferredNationality: [],
    maxContracts: 999,
    riskTolerance: 0.90,
    loyaltyFactor: 0.20,
    personality: BRAND_PERSONALITIES.UNDERDOG_PATRON,
    conservativeImage: false,
    energyBrand: false,
    luxuryBrand: false,
    description: 'Loja de entry-level. Assina qualquer jogador com ranking e visibilidade mínimos.',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS DE ACESSO
// ─────────────────────────────────────────────────────────────────────────────

/** Retorna o perfil de um patrocinador pelo id */
export function getSponsorById(id) {
  return SPONSOR_CATALOG.find(s => s.id === id) ?? null;
}

/** Retorna todas as marcas de uma categoria */
export function getSponsorsByCategory(category) {
  return SPONSOR_CATALOG.filter(s => s.category === category);
}

/** Retorna todas as marcas de um tier */
export function getSponsorsByTier(tier) {
  return SPONSOR_CATALOG.filter(s => s.tier === tier);
}

/** Retorna o objeto SPONSOR_TIERS para um id de tier */
export function getTierData(tierId) {
  return SPONSOR_TIERS[tierId] ?? SPONSOR_TIERS.ENTRY;
}

/** Retorna a faixa de contrato esperada para um tier (em USD/ano) */
export function getContractRange(tierId) {
  return getTierData(tierId).contractRange;
}
